---
sidebar: sidebar 
permalink: oracle/virtualization/intro.html 
keywords: oracle, database, ontap, virtualization, esx, hyper-v, KVM 
summary: Introducción a la virtualización de bases de datos 
---
= Virtualización
:allow-uri-read: 


[role="lead"]
La virtualización de bases de datos con VMware ESX, Oracle OVM o KVM es una opción cada vez más común para los clientes de NetApp que eligieron la virtualización incluso para las bases de datos más importantes.

Existen muchos malentendidos sobre las normativas de compatibilidad de la virtualización, especialmente respecto a los productos VMware. De hecho, no es raro saber que Oracle no admite la virtualización de ningún modo. Esta noción es incorrecta y conduce a la pérdida de oportunidades para la virtualización. El ID de documento de Oracle 249212,1 analiza los problemas conocidos en un entorno de Oracle y también especifica el soporte para RAC.

Es posible que se solicite a un cliente con un problema desconocido para Oracle que reproduzca el problema en el hardware físico. Es posible que un cliente de Oracle que ejecuta una versión de borde de sangrado de un producto no desee utilizar la virtualización debido a la posibilidad de detectar nuevos errores. Sin embargo, esta situación no ha sido un problema en la práctica para los clientes de virtualización que utilizan versiones de producto generalmente disponibles.



== Presentación de almacenamiento

Los clientes que están considerando la virtualización de sus bases de datos deben basar sus decisiones sobre almacenamiento en sus necesidades empresariales. Aunque esta es una afirmación generalmente verdadera para todas las decisiones DE TI, es especialmente importante para la virtualización, porque el tamaño y el alcance de los proyectos varían considerablemente.

Existen cuatro opciones básicas para la presentación del almacenamiento:

* LUN iSCSI gestionadas por el iniciador iSCSI en la máquina virtual, no el hipervisor
* Sistemas de archivos NFS montados por la máquina virtual, no un disco de máquina virtual (VMDK)
* Almacenes de datos de hipervisor


Como regla general, evite el uso de almacenes de datos para archivos de Oracle. Hay muchas razones para esta recomendación:

* *Transparencia.* Cuando una VM posee sus sistemas de archivos, es más fácil para un administrador de bases de datos o un administrador del sistema identificar el origen de los sistemas de archivos para sus datos.
* *Rendimiento.* Las pruebas han demostrado que hay un efecto de rendimiento al canalizar todas las E/S a través de un almacén de datos de hipervisor.
* *Capacidad de gestión.* Cuando una VM es propietaria de sus sistemas de archivos, el uso o no uso de una capa de hipervisor afecta a la capacidad de gestión. Los mismos procedimientos para aprovisionamiento, supervisión, protección de datos, etc. se pueden utilizar en todo el conjunto, incluidos los entornos virtualizados y no virtualizados.
* *Estabilidad y resolución de problemas.* Cuando una VM es propietaria de sus sistemas de archivos, ofrecer un rendimiento bueno y estable y solucionar problemas es mucho más simple porque toda la pila de almacenamiento está presente en la VM. El único rol del hipervisor es transportar tramas FC o IP. Cuando se incluye un almacén de datos en una configuración, esto complica la configuración introduciendo otro conjunto de tiempos de espera, parámetros, archivos de registro y posibles errores.
* *Portabilidad.* Cuando una VM posee sus sistemas de archivos, el proceso de mover un entorno de Oracle se vuelve mucho más sencillo. Los sistemas de archivos se pueden mover fácilmente entre huéspedes virtualizados y no virtualizados.
* * El bloqueo del proveedor.* Después de colocar los datos en un almacén de datos, usar un hipervisor diferente o extraer los datos del entorno virtualizado se vuelve completamente difícil.
* *Activación de instantáneas.* En algunos casos, las copias de seguridad en un entorno virtualizado pueden convertirse en un problema debido al ancho de banda relativamente limitado. Por ejemplo, un tronco 10GbE de cuatro puertos podría ser suficiente para responder a las necesidades de rendimiento diario de muchas bases de datos virtualizadas. Sin embargo, tal tronco sería insuficiente para realizar copias de seguridad con RMAN u otros productos de copia de seguridad que requieran una copia de tamaño completo de los datos.
+
El uso de sistemas de archivos propiedad de máquinas virtuales facilita la utilización de los backups y las restauraciones basados en Snapshot. Un sistema de archivos propiedad de un equipo virtual libera el trabajo de realizar backups en el sistema de almacenamiento. No es necesario sobrecargar la configuración del hipervisor únicamente para admitir los requisitos de ancho de banda y CPU en la ventana de backup.




TIP: *NetApp recomienda* evitar colocar los datos de Oracle en un almacén de datos para lograr un rendimiento y una gestión óptimos. Utilice sistemas de archivos propiedad del huésped, como sistemas de archivos NFS o iSCSI gestionados por el invitado o con RDM.



== Controladores paravirtualizados

Para un rendimiento óptimo, el uso de controladores de red paravirtualizados es fundamental. Cuando se utiliza un almacén de datos, se requiere un controlador SCSI paravirtualizado. Un controlador de dispositivo paravirtualizado permite a un invitado integrarse más profundamente en el hipervisor, en lugar de un controlador emulado en el que el hipervisor pasa más tiempo de CPU imitando el comportamiento del hardware físico.

El rendimiento de la mayoría de las bases de datos está limitado por el almacenamiento. Por lo tanto, la latencia adicional introducida por un controlador de red o SCSI es particularmente notable. El servicio de atención al cliente de NetApp ha encontrado muchas quejas de rendimiento que se resolvieron mediante la instalación de controladores paravirtualizados. Durante la prueba de concepto de un cliente, las bases de datos mostraron un mejor rendimiento bajo ESX que si se ejecutaba el mismo hardware como «bare metal». Las pruebas realizaron grandes cargas de I/O y la diferencia de rendimiento se atribuyó al uso de controladores de red paravirtualizados ESX.


TIP: *NetApp recomienda* usar siempre controladores de red paravirtualizados y controladores SCSI.



== RAM de sobrecompromiso

Sobrecomprometer RAM significa configurar más RAM virtualizada en varios hosts de la que existe en el hardware físico. Si lo hace, se pueden producir problemas de rendimiento inesperados. Al virtualizar una base de datos, el hipervisor no debe intercambiar los bloques subyacentes del SGA de Oracle en el almacenamiento. Si lo hace, los resultados de rendimiento son muy inestables.


TIP: *NetApp recomienda* no configurar un hipervisor de manera que permita intercambiar bloques SGA de Oracle.
