---
sidebar: sidebar 
permalink: oracle/oracle-storage-san-config-lun-alignment.html 
keywords: SAN, ASM, LVM 
summary: Alineación de LUN con bases de datos de Oracle 
searchtitle: Alineación de LUN para I/O de bases de datos de Oracle 
---
= Alineación de LUN
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La alineación de LUN hace referencia a optimizar las I/O con respecto al diseño del sistema de archivos subyacente.

Directiva no resuelta en <stdin> - Incluir::lun-alignment.adoc[]

Consulte también la discusión sobre la alineación de los bloques de compresión en la sección link:oracle-ontap-config-efficiency.html["Eficiencia"]. Cualquier diseño alineado con los límites de bloques de compresión de 8KB KB también se alineará con los límites de 4KB KB.



== Advertencias de desalineación

Directiva no resuelta en <stdin> - Include::database-misalignment-warnings.adoc[]

La alineación en entornos Solaris es más complicada. Consulte http://support.netapp.com/documentation/productlibrary/index.html?productID=61343["Configuración de host SAN ONTAP"^] si quiere más información.

|===
| Precaución 


| En entornos Solaris x86, tenga cuidado adicional con la alineación correcta, ya que la mayoría de las configuraciones tienen varias capas de particiones. Los segmentos de partición de Solaris x86 normalmente existen en la parte superior de una tabla de particiones de registro de inicio maestro estándar. 
|===