---
sidebar: sidebar 
permalink: oracle/oracle-dp-consistency-group-backup.html 
keywords: oracle, data, protection, consistency, group, backup, volume, archive, log, redo, controlfiles 
summary: Backups de grupos de coherencia para bases de datos de Oracle en ONTAP 
---
= Backups de grupos de coherencia de base de datos de Oracle
:allow-uri-read: 


[role="lead"]
Para realizar el backup más sencillo posible, sólo coloque toda la base de datos de Oracle en un único volumen ONTAP

La protección de los archivos de datos, los registros de archivo, los registros de recuperación y los archivos de control con una única snapshot es un método válido de copia de seguridad, restauración y replicación.  Sin embargo, el RPO se limita al punto del propio backup. Es adecuado para un objetivo de punto de recuperación de una hora o superior. Si una base de datos abarca volúmenes, se necesitan cg-snapshots utilizando una de las herramientas descritas anteriormente.

A modo de ejemplo, toda la base de datos puede estar en un solo volumen con la siguiente programación Snapshot:

* 72 snapshots cada hora
* 30 snapshots por noche
* 12 snapshots mensuales


Esto proporciona un objetivo de punto de recuperación de una hora durante el período de implementación de las 72 horas anteriores, además de backups adicionales mensuales y nocturnos. También se pueden incluir varias bases de datos o archivos de aplicaciones en el único volumen o conjunto de snapshots de cg para ofrecer backups consistentes en un entorno mayor.
