---
permalink: oracle/oracle-asar2-app-config-mbr.html 
sidebar: sidebar 
keywords: oracle, database, ASA r2, ontap, db_file_multiblock_read_count, multiblock 
summary: 'Parámetros de base de datos Oracle: db_file_multiblock_read_count con ASA r2' 
searchtitle: 'Parámetros de base de datos Oracle: db_file_multiblock_read_count con ASA r2' 
---
= db_file_multibloque_read_count
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La `db_file_multiblock_read_count` El parámetro controla el Núm. Máximo de bloques de bases de datos Oracle que Oracle lee como una sola operación durante la E/S secuencial

No hay cambios en las recomendaciones en comparación con los sistemas AFF/ FAS . El comportamiento de ONTAP y las mejores prácticas de Oracle siguen siendo idénticas en las plataformas ASA r2, AFF y FAS .

Sin embargo, este parámetro no afecta a la cantidad de bloques que Oracle lee durante cualquier operación de lectura ni afecta a las operaciones de lectura aleatorias Solo se ve afectado el tamaño de bloque de I/O secuencial.

Oracle recomienda que el usuario deje este parámetro sin definir. Al hacerlo, el software de la base de datos puede definir automáticamente el valor óptimo. Por lo general, este parámetro se establece en un valor que proporciona un tamaño de I/O de 1MB. Por ejemplo, una lectura de 1MB de bloques de 8KB requeriría la lectura de 128 bloques y el valor predeterminado de este parámetro sería, por lo tanto, de 128.

La mayoría de los problemas de rendimiento de la base de datos observados por NetApp en los sitios de los clientes implican una configuración incorrecta para este parámetro. Hay motivos válidos para cambiar este valor con las versiones 8 y 9 de Oracle. Como resultado, el parámetro puede estar presente sin saberlo en `init.ora` Archivos porque la base de datos se actualizó in situ a Oracle 10 y versiones posteriores. Una configuración heredada de 8 o 16, en comparación con el valor predeterminado de 128, daña significativamente el rendimiento de I/O secuencial.


TIP: *NetApp recomienda* configurar el `db_file_multiblock_read_count` el parámetro no debe estar presente en el `init.ora` archivo. NetApp nunca se ha encontrado con una situación en la que cambiar este parámetro mejoró el rendimiento, pero hay muchos casos en los que causó daños claros en el rendimiento de I/O secuencial.
