---
sidebar: sidebar 
permalink: oracle/oracle-tiering-whole-file.html 
keywords: tiering, fabricpool 
summary: Organización en niveles de FabricPool de archivos completos en bases de datos de Oracle 
---
= Organización en niveles de FabricPool de archivos completos en bases de datos de Oracle
:allow-uri-read: 


[role="lead"]
Aunque la organización en niveles de FabricPool opera a nivel de bloques, en algunos casos se puede utilizar para la organización en niveles de archivos.

Muchas aplicaciones están organizadas por fecha, y por lo general es menos probable que se acceda a estos datos a medida que envejecen. Por ejemplo, un banco puede tener un repositorio de archivos PDF que contenga cinco años de extractos de clientes, pero sólo están activos los últimos meses. FabricPool se puede usar para reubicar archivos de datos más antiguos en el nivel de capacidad. Un período de enfriamiento de 14 días garantizaría que los 14 días más recientes de archivos PDF permanezcan en el nivel de rendimiento. Además, los archivos que se leen al menos cada 14 días permanecerán activos y, por consiguiente, permanecerán en el nivel de rendimiento.



== Normativas

Para implementar un método de organización en niveles basado en archivos, debe tener archivos que se escriban y no se modifiquen posteriormente. La `tiering-minimum-cooling-days` la política debe establecerse lo suficientemente alta para que los archivos que pueda necesitar permanezcan en el nivel de rendimiento. Por ejemplo, un conjunto de datos para los que se requieren los 60 días de datos más recientes y un rendimiento óptimo garantiza configurar el `tiering-minimum-cooling-days` hasta 60. También se pueden obtener resultados similares en función de los patrones de acceso a archivos. Por ejemplo, si se requieren los últimos 90 días de datos y la aplicación accede a ese intervalo de 90 días, los datos permanecerán en el nivel de rendimiento. Mediante la configuración de `tiering-minimum-cooling-days` en el periodo 2, se obtiene una organización en niveles inmediata después de que los datos se vuelven menos activos.

La `auto` se requiere una política para impulsar la organización en niveles de estos bloques porque solo el `auto` la política afecta a los bloques que están en el sistema de archivos activo.


NOTE: Cualquier tipo de acceso a los datos restablece los datos del mapa de calor. La detección de virus, la indexación e incluso la actividad de backup que lee los archivos de origen evita la segmentación, ya que es necesario `tiering-minimum-cooling-days` nunca se ha alcanzado el umbral.
