---
sidebar: sidebar 
permalink: oracle/oracle-migration-overview.html 
keywords: oracle, ontap, migrations, TR-4534 
summary: Introducción a la migración del almacenamiento de Oracle 
---
= Migración de bases de datos de Oracle a sistemas de almacenamiento de NetApp
:allow-uri-read: 


[role="lead"]
El aprovechamiento de las funciones de una nueva plataforma de almacenamiento tiene un requisito inevitable: Los datos deben estar situados en el nuevo sistema de almacenamiento.


NOTE: Esta documentación sustituye al informe técnico _TR-4534: Migración de bases de datos de Oracle a sistemas de almacenamiento de NetApp_

En el caso de un nuevo proyecto de base de datos, no se trata de un problema, ya que los entornos de bases de datos y aplicaciones están construidos in situ. Sin embargo, la migración plantea desafíos especiales con respecto a la interrupción del negocio, el tiempo necesario para completar la migración, las habilidades necesarias y la minimización de riesgos.



== Scripts

En esta documentación se proporcionan secuencias de comandos de ejemplo. Estos scripts proporcionan métodos de ejemplo de automatización de diversos aspectos de la migración para reducir la posibilidad de errores de usuario. Las secuencias de comandos pueden reducir las demandas generales sobre el PERSONAL DE TI responsable de la migración y pueden acelerar el proceso general. Todos estos scripts se extraen de los proyectos de migración reales realizados por los servicios profesionales de NetApp y los partners de NetApp. A lo largo de esta documentación se muestran ejemplos de su uso.
