---
sidebar: sidebar 
permalink: oracle/oracle-ontap-config-thin-provisioning.html 
keywords: thin provisioning, oracle 
summary: Thin Provisioning de Oracle y ONTAP 
searchtitle: Thin provisioning con bases de datos de Oracle 
---
= Aprovisionamiento ligero
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El thin provisioning para una base de datos de Oracle requiere una planificación cuidadosa porque el resultado es configurar más espacio en un sistema de almacenamiento del que necesariamente está disponible físicamente. Vale mucho la pena el esfuerzo porque, cuando se hace correctamente, el resultado es un ahorro significativo de costes y mejoras en la capacidad de gestión.

El thin provisioning se presenta de muchas formas y forma parte de muchas de las funciones que ofrece ONTAP para un entorno de aplicaciones empresariales. Además, thin provisioning está estrechamente relacionado con las tecnologías de eficiencia por el mismo motivo: Las funciones de eficiencia permiten almacenar más datos lógicos de lo que existen técnicamente en el sistema de almacenamiento.

Casi cualquier uso de las copias Snapshot implica thin provisioning. Por ejemplo, una base de datos de 10TB TB típica en almacenamiento de NetApp incluye unos 30 días de copias Snapshot. Este arreglo da como resultado aproximadamente 10TB TB de datos visibles en el sistema de archivos activo y 300TB TB dedicados a las copias snapshot. El total de 310TB TB de almacenamiento suele residir en aproximadamente 12TB a 15TB GB de espacio. La base de datos activa consume 10TB GB y los 300TB TB restantes solo requieren de 2TB a 5TB GB de espacio, ya que solo se almacenan los cambios realizados en los datos originales.

La clonación es también un ejemplo de aprovisionamiento ligero. Un importante cliente de NetApp creó 40 clones de una base de datos de 80TB para que los utilizara el equipo de desarrollo. Si los 40 desarrolladores que utilizan estos clones sobrescribieran cada bloque en cada archivo de datos, se necesitarían más de 3,2PB GB de almacenamiento. En la práctica, la rotación es baja y el requisito de espacio colectivo se acerca a 40TB, ya que solo se almacenan cambios en las unidades.



== Gestión del espacio

Se debe tener cierta precaución con el thin provisioning de un entorno de aplicaciones porque las tasas de cambios de los datos pueden aumentar de forma inesperada. Por ejemplo, el consumo de espacio debido a las instantáneas puede aumentar rápidamente si se reindexan las tablas de la base de datos o si se aplican parches a gran escala a los huéspedes de VMware. Una copia de seguridad fuera de lugar puede escribir una gran cantidad de datos en muy poco tiempo. Por último, puede ser difícil recuperar algunas aplicaciones si un sistema de archivos se queda sin espacio libre inesperadamente.

Afortunadamente, estos riesgos se pueden abordar con una cuidadosa configuración de `volume-autogrow` y.. `snapshot-autodelete` normativas. Como sus nombres implican, estas opciones permiten al usuario crear políticas que desactiven automáticamente el espacio consumido por las copias Snapshot o aumentar un volumen para alojar datos adicionales. Hay muchas opciones disponibles y las necesidades varían según el cliente.

Consulte link:https://docs.netapp.com/us-en/ontap/volumes/index.html["documentación de gestión de almacenamiento lógico"] para obtener un análisis completo de estas funciones.



== Reservas fraccionarias

La reserva fraccionaria es el comportamiento de una LUN en un volumen con respecto a la eficiencia del espacio. Cuando la opción `fractional-reserve` se establece en 100 %, todos los datos del volumen pueden experimentar una rotación del 100 % con cualquier patrón de datos sin agotar el espacio en el volumen.

Por ejemplo, piense en una base de datos en un único LUN de 250GB GB en un volumen de 1TB GB. La creación de una instantánea provocaría de inmediato la reserva de 250GB GB de espacio adicional en el volumen para garantizar que el volumen no se quede sin espacio por ningún motivo. El uso de reservas fraccionarias suele ser un desperdicio debido a que es extremadamente poco probable que cada byte del volumen de base de datos deba sobrescribirse. No hay razón para reservar espacio para un evento que nunca ocurre. Sin embargo, si un cliente no puede supervisar el consumo de espacio en un sistema de almacenamiento y debe tener la seguridad de que nunca se agota el espacio, se necesitarían reservas fraccionarias del 100% para utilizar copias Snapshot.



== Compresión y deduplicación

La compresión y la deduplicación son ambas formas de thin provisioning. Por ejemplo, una huella de datos de 50TB MB puede comprimirse hasta 30TB MB, lo que supone un ahorro de 20TB MB. Para que la compresión proporcione beneficios, algunos de esos 20TB MB deben utilizarse para otros datos o el sistema de almacenamiento debe adquirirse con menos de 50TB TB. El resultado es almacenar más datos de los que están disponibles técnicamente en el sistema de almacenamiento. Desde el punto de vista de los datos, hay 50TB GB de datos, a pesar de que ocupa solo 30TB GB en las unidades.

Siempre existe la posibilidad de que cambie la capacidad de compresión de un conjunto de datos, lo que provocaría un aumento del consumo de espacio real. Este aumento del consumo significa que la compresión debe gestionarse como sucede con otras formas de thin provisioning en términos de supervisión y uso `volume-autogrow` y.. `snapshot-autodelete`.

La compresión y la deduplicación se tratan de forma más detallada en el enlace de sección:efficiency.html



=== Compresión y reservas fraccionarias

La compresión es una forma de thin provisioning. Las reservas fraccionarias afectan al uso de la compresión, con una nota importante; se reserva espacio con antelación para la creación de la instantánea. Normalmente, la reserva fraccionaria sólo es importante si existe una instantánea. Si no hay ninguna instantánea, la reserva fraccionaria no es importante. Este no es el caso con la compresión. Si se crea una LUN en un volumen con compresión, ONTAP conserva el espacio para acomodar una copia de Snapshot. Este comportamiento puede ser confuso durante la configuración, pero es esperado.

Como ejemplo, piense en un volumen de 10GB GB con una LUN de 5GB TB que se ha comprimido en 2,5GB sin copias Snapshot. Considere estos dos escenarios:

* La reserva fraccionaria = 100 da como resultado el uso de 7,5GB
* La reserva fraccionaria = 0 da como resultado el uso de 2,5GB


El primer escenario incluye 2,5GB GB de consumo de espacio para los datos actuales y 5GB GB de espacio para representar una rotación del 100% de la fuente antes del uso de la tecnología Snapshot. El segundo escenario no reserva espacio extra.

Aunque esta situación pueda parecer confusa, es poco probable que se encuentre en la práctica. La compresión implica thin provisioning y thin provisioning de un entorno de LUN requiere reservas fraccionarias. Siempre es posible que los datos comprimidos se sobrescriban en algo que no se pueda comprimir, lo que significa que un volumen debe estar aplicado mediante thin provisioning para que la compresión produzca ahorro.

[TIP]
====
*NetApp recomienda* las siguientes configuraciones de reserva:

* Configurado `fractional-reserve` a 0 cuando se implementa la supervisión de la capacidad básica junto con `volume-autogrow` y.. `snapshot-autodelete`.
* Configurado `fractional-reserve` a 100 si no hay capacidad de monitoreo o si es imposible agotar el espacio bajo cualquier circunstancia.


====


== Espacio libre y asignación de espacio LVM

La eficiencia del thin provisioning de las LUN activas en un entorno de sistema de archivos se puede perder con el tiempo a medida que se eliminan los datos. A menos que los datos eliminados se sobrescriban con ceros (consulte también link:oracle-storage-san-config-asmru.html["ASMRU"] O bien, el espacio se libera con la recuperación de espacio TRIM/UNMAP, los datos «borrados» ocupan cada vez más espacio en blanco sin asignar en el sistema de archivos. Además, el thin provisioning de LUN activos es de uso limitado en muchos entornos de bases de datos, ya que los archivos de datos se inicializan en su tamaño completo en el momento de la creación.

Una planificación cuidadosa de la configuración de LVM puede mejorar la eficiencia y minimizar la necesidad de aprovisionar el almacenamiento y redimensionar las LUN. Cuando se utiliza un LVM como Veritas VxVM u Oracle ASM, los LUN subyacentes se dividen en extensiones que solo se utilizan cuando es necesario. Por ejemplo, si un conjunto de datos empieza con un tamaño de 2TB GB, pero podría crecer hasta 10TB TB con el tiempo, este conjunto de datos podría colocarse en 10TB LUN con thin provisioning organizados en un grupo de discos de LVM. Ocuparía solo 2TB GB de espacio en el momento de la creación y solo reclamaría espacio adicional a medida que se asignan extensiones para acomodar el crecimiento de los datos. Este proceso es seguro siempre y cuando se supervise el espacio.
