---
sidebar: sidebar 
permalink: oracle/oracle-dr-snapmirror-cg.html 
keywords: oracle, data protection, DR, CG 
summary: Replicación de grupo de coherencia para bases de datos de Oracle 
---
= Recuperación ante desastres de grupo de consistencia
:allow-uri-read: 


[role="lead"]
La replicación de grupo de consistencia puede ser tan sencilla como programar la replicación de un único volumen a través de SnapMirror. Esto incluye archivos de datos, archivos de control, archive logs y redo logs. Cada actualización de SnapMirror genera una nueva copia de la base de datos en el sitio de destino que resulta coherente y está lista para la activación interrumpiendo el mirroring.

Donde una base de datos debe abarcar volúmenes, se requiere una snapshot de grupo de coherencia (cg-snapshot).

Otra ventaja de esta estrategia cuando se usa con SnapMirror en el modo de replicación de nivel de bloque es la replicación completa de todas las instantáneas del sistema de almacenamiento de origen. Además de la copia de recuperación ante desastres, se replica todo el complemento de backups.
