---
sidebar: sidebar 
permalink: mssql/mssql-disaster-recovery.html 
keywords: MS-SQL,mssql,SQL Server, disaster recovery, snapmirror 
summary: Microsoft SQL Server en ONTAP 
---
= Recuperación ante desastres de Microsoft SQL Server
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
NetApp ofrece varios enfoques para aumentar la disponibilidad de los datos en caso de un fallo de hardware, software o en el sitio.



== SnapMirror de NetApp

La tecnología SnapMirror de NetApp ofrece una solución empresarial rápida y flexible para el mirroring o la replicación de datos sobre LAN y WAN. La tecnología SnapMirror solo transfiere los bloques de datos 4KB modificados al destino tras la transferencia base inicial, lo que reduce significativamente los requisitos de ancho de banda de red. SnapMirror ofrece una replicación asíncrona a nivel de volumen basada en un intervalo de actualización de replicación configurado.
Las siguientes son recomendaciones para SnapMirror para SQL Server:

* Si se usa CIFS, la SVM de destino debe ser miembro del mismo dominio de Active Directory al que pertenece la SVM de origen para que las listas de control de acceso (ACL) almacenadas en archivos NAS no se interrumpan durante la recuperación de un desastre.
* No es necesario usar nombres de volúmenes de destino iguales a los nombres de los volúmenes de origen, pero puede simplificar la gestión del proceso de montaje de los volúmenes de destino en el destino. Si se utiliza CIFS, debe hacer que el espacio de nombres NAS de destino sea idéntico en rutas y la estructura de directorios para el espacio de nombres de origen.
* Para fines de coherencia, no programe una actualización de SnapMirror de las controladoras. No obstante, habilite la actualización de SnapMirror de SnapCenter para actualizar SnapMirror después de que se complete el backup completo o de registro.
* Distribuya los volúmenes que contienen datos de SQL Server en diferentes nodos del clúster para permitir que todos los nodos del clúster compartan la actividad de replicación de SnapMirror. Esta distribución optimiza el uso de los recursos de los nodos.


Para obtener más información acerca de SnapMirror, consulte link:https://www.netapp.com/us/media/tr-4015.pdf["TR-4015: Guía de configuración de SnapMirror y prácticas recomendadas para ONTAP 9"^].
