---
sidebar: sidebar 
permalink: mssql/mssql-shared-vs-dedicated.html 
keywords: MSSQL,SQL Server, multiple instances, dedicated instance, ONTAP 
summary: Puesta en marcha de instancias de Microsoft SQL Server 
---
= Instancia compartida de Microsoft SQL Server frente a instancia dedicada
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Se pueden configurar varios SQL Server como una única instancia por servidor o como varias instancias. La decisión correcta generalmente depende de factores como si el servidor se va a utilizar para la producción o el desarrollo, si la instancia se considera crítica para las operaciones de negocio y los objetivos de rendimiento.

Las configuraciones de instancias compartidas pueden ser inicialmente más fáciles de configurar, pero pueden provocar problemas en los que los recursos se dividen o bloquean, lo que a su vez provoca problemas de rendimiento para otras aplicaciones que tienen bases de datos alojadas en la instancia compartida de SQL Server.

La solución de problemas de rendimiento puede ser complicada porque debe averiguar qué instancia es la causa raíz. Esta pregunta se compara con los costes de las licencias del sistema operativo y de las licencias de SQL Server. Si el rendimiento de las aplicaciones es primordial, se recomienda encarecidamente utilizar una instancia dedicada.

Microsoft concede licencias de SQL Server por núcleo a nivel de servidor y no por instancia. Por este motivo, los administradores de bases de datos se ven tentados a instalar tantas instancias de SQL Server como el servidor pueda manejar para ahorrar en costes de licencias, lo que puede ocasionar mayores problemas de rendimiento más adelante.


TIP: *NetApp recomienda* elegir instancias dedicadas de SQL Server siempre que sea posible para obtener un rendimiento óptimo.
