---
sidebar: sidebar 
permalink: mssql/mssql-overview.html 
keywords: MS-SQL,mssql,SQL Server,TR-4590 
summary: Microsoft SQL Server en ONTAP 
---
= Descripción general de Microsoft SQL Server
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
SQL Server es la base de la plataforma de datos de Microsoft y ofrece rendimiento de misión crítica con tecnologías en memoria y información más rápida sobre cualquier dato, ya sea en las instalaciones o en el cloud.


NOTE: Esta documentación sustituye al informe técnico publicado previamente _TR-4590: Guía de mejores prácticas para Microsoft SQL Server con ONTAP_

Microsoft SQL Server aprovecha las funciones de misión crítica que se ofrecen en versiones anteriores al proporcionar un rendimiento, disponibilidad y capacidad de gestión excepcionales para aplicaciones esenciales. El sistema de almacenamiento es un factor clave en el rendimiento general de una base de datos de SQL Server. NetApp proporciona varios productos para permitir que su base de datos de SQL Server proporcione un rendimiento empresarial a la vez que proporciona herramientas de primera calidad para gestionar su entorno.



== Propósito y alcance

En esta sección se describen las mejores prácticas y se ofrece una visión de las consideraciones de diseño para la puesta en marcha de SQL Server en sistemas de almacenamiento NetApp que ejecuten el software NetApp ONTAP, con el objetivo de lograr una instalación de almacenamiento efectiva y eficiente y una planificación completa de protección y retención de datos. El alcance de esta guía se limita a directrices de diseño técnicas basadas en los principios de diseño y los estándares preferidos que NetApp recomienda para su infraestructura de almacenamiento al poner en marcha SQL Server. La aplicación integral está fuera del alcance de este informe.

Las mejores prácticas y las recomendaciones descritas en esta guía permiten a los arquitectos de SQL Server y los administradores de almacenamiento NetApp planificar un entorno de SQL Server de alta disponibilidad y fácil de gestionar y cumplir con los exigentes acuerdos de nivel de servicios. NetApp asume que el lector tiene conocimiento práctico de lo siguiente:

* Software NetApp ONTAP
* NetApp SnapCenter como software de backup, que incluye:
+
** Plugin de SnapCenter para Microsoft Windows
** Plugin de SnapCenter para SQL Server


* Arquitectura y administración de Microsoft SQL Server


Para obtener información sobre la compatibilidad de la configuración en la pila de NetApp, consulte link:http://mysupport.netapp.com/NOW/products/interoperability/["Herramienta de matriz de interoperabilidad de NetApp (IMT)"^].
