---
sidebar: sidebar 
permalink: mssql/mssql-data-protection.html 
keywords: MSSQL,SQL Server, SnapCenter, data protection, app-consistent backup, ONTAP 
summary: Protección de bases de datos de Microsoft SQL Server en ONTAP con comandos SnapCenter y T-SQL. 
---
= Protección de datos de Microsoft SQL Server con el software de gestión NetApp
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
La planificación del backup de la base de datos se basa en los requisitos del negocio. Al combinar la tecnología Snapshot de NetApp de ONTAP y el aprovechamiento de las API de Microsoft SQL Server, puede realizar rápidamente backup consistente con las aplicaciones independientemente del tamaño de las bases de datos del usuario. Para obtener requisitos de gestión de datos más avanzados o de escalado horizontal, NetApp ofrece SnapCenter.



== SnapCenter

SnapCenter es el software de protección de datos de NetApp para aplicaciones empresariales. Las bases de datos de SQL Server pueden protegerse de forma rápida y fácil con el complemento de SnapCenter para SQL Server y con operaciones de sistema operativo gestionadas por el plugin de SnapCenter para Microsoft Windows.

La instancia de SQL Server puede ser una configuración independiente, una instancia de clúster de conmutación por error o puede estar siempre en un grupo de disponibilidad. El resultado es que, a partir de un solo panel, las bases de datos pueden protegerse, clonarse y restaurarse a partir de copias principales o secundarias. SnapCenter puede gestionar bases de datos de SQL Server tanto en las instalaciones, en el cloud como en configuraciones híbridas.Las copias de bases de datos también se pueden crear en pocos minutos en el host original o alternativo para fines de desarrollo o generación de informes.


TIP: *NetApp recomienda* usar SnapCenter para crear copias snapshot. También funciona el método de T-SQL descrito a continuación, pero SnapCenter ofrece una automatización completa del proceso de backup, restauración y clonación. También realiza una detección para garantizar que se crean las snapshots correctas. No se necesita ninguna configuración previa.
...
SQL Server también requiere coordinación entre el SO y el almacenamiento para garantizar que los datos correctos están presentes en las snapshots en el momento de la creación. En la mayoría de los casos, el único método seguro para hacerlo es con SnapCenter o T-SQL. Es posible que las instantáneas creadas sin esta coordinación adicional no se puedan recuperar de forma fiable.

Para obtener más detalles sobre el plugin de SQL Server para SnapCenter, consulte link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714: Guía de mejores prácticas para SQL Server con NetApp SnapCenter"^].



== Protección de la base de datos mediante instantáneas de T-SQL

En SQL Server 2022, Microsoft introdujo las copias Snapshot de T-SQL que ofrecen una ruta para el scripting y la automatización de las operaciones de backup. En lugar de realizar copias de tamaño completo, puede preparar la base de datos para instantáneas. Una vez que la base de datos está lista para el backup, se pueden aprovechar las API DE REST DE ONTAP para crear snapshots.

A continuación, se muestra un flujo de trabajo de backup de ejemplo:

. Congelar una base de datos con el comando ALTER. Esto prepara la base de datos para una instantánea coherente en el almacenamiento subyacente. Después de congelar, puede descongelar la base de datos y registrar la instantánea con el comando BACKUP.
. Realice copias Snapshot de varias bases de datos en los volúmenes de almacenamiento de forma simultánea con los nuevos comandos DEL GRUPO DE BACKUP y DEL SERVIDOR DE BACKUP.
. Realice copias de seguridad COMPLETAS o copias de seguridad COMPLETAS COPY_ONLY. Estas copias de seguridad también se registran en msdb.
. Llevar a cabo una recuperación puntual mediante backups de registro realizados con el método de streaming normal después del backup COMPLETO de la instantánea. Las copias de seguridad diferenciales de transmisión también se admiten si se desea.


Para obtener más información, consulte link:https://learn.microsoft.com/en-us/sql/relational-databases/databases/create-a-database-snapshot-transact-sql?view=sql-server-ver16["Documentación de Microsoft para conocer las instantáneas de T-SQL"^].
