---
sidebar: sidebar 
permalink: mssql/mssql-disaster-recovery.html 
keywords: MSSQL,SQL Server, disaster recovery, snapmirror 
summary: Recuperación ante desastres de Microsoft SQL Server con ONTAP 
---
= Recuperación ante desastres de Microsoft SQL Server con ONTAP
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Las bases de datos empresariales y las infraestructuras de aplicaciones a menudo requieren la replicación para protegerse de desastres naturales o de la interrupción inesperada del negocio con un tiempo de inactividad mínimo.

La función de replicación de grupos de disponibilidad siempre disponible de SQL Server puede ser una opción excelente, y NetApp ofrece opciones para integrar la protección de datos con disponibilidad permanente. Sin embargo, en algunos casos es posible que desee considerar la tecnología de replicación de ONTAP. Hay tres opciones básicas.



== SnapMirror

La tecnología SnapMirror ofrece una solución empresarial rápida y flexible para replicar datos en LAN y WAN. La tecnología SnapMirror solo transfiere los bloques de datos modificados al destino una vez que se creó el reflejo inicial, lo que reduce considerablemente los requisitos de ancho de banda de la red. Puede configurarse tanto en modo síncrono como asíncrono.



== NetApp MetroCluster

Las configuraciones de MetroCluster ayudan a ofrecer soluciones de almacenamiento de alta disponibilidad y cero pérdida de datos para aplicaciones, bases de datos y plataformas de virtualización. La solución se implementa con una combinación de clustering basado en cabinas y replicación síncrona que proporciona una capa adicional de protección para todo el entorno de host y almacenamiento.



== Sincronización activa de SnapMirror (anteriormente, SnapMirror Business Continuity)

La sincronización activa de SnapMirror se basa en SnapMirror síncrono y su funcionalidad para replicar varios LUN para replicar el almacenamiento mientras mantiene la consistencia de orden de escritura. Con MetroCluster, la controladora ONTAP, incluida la configuración de red, debe ser idéntica en los distintos sitios. Con la sincronización activa de SnapMirror, básicamente cuenta con dos sistemas ONTAP diferentes que mantienen copias independientes de los datos de su unidad lógica, pero que cooperan para presentar una única instancia de esa LUN. Desde el punto de vista del host, se trata de una única entidad de LUN.

La principal diferencia entre la sincronización activa de MetroCluster y SnapMirror es la granularidad y la escalabilidad. Si solo tiene que seleccionar cargas de trabajo específicas para que se repliquen sincrónicamente o los LUN deben estar disponibles en ambos sitios para las operaciones de lectura y escritura, la sincronización activa de SnapMirror es la mejor opción. Si necesita replicar entornos enteros o incluso centros de datos, MetroCluster es una opción mejor. Además, SnapMirror Active Sync es actualmente solo para SAN, mientras que MetroCluster tiene un protocolo multiprotocolo, incluidos SAN, NFS y SMB.

Para obtener más información sobre SnapMirror, consulte link:https://www.netapp.com/pdf.html?item=/media/17229-tr4015pdf.pdf["TR-4015: Guía de configuración de SnapMirror y prácticas recomendadas para ONTAP 9"^].
