---
sidebar: sidebar 
permalink: mssql/mssql-disaster-recovery.html 
keywords: MSSQL,SQL Server, disaster recovery, snapmirror 
summary: Recuperación ante desastres de Microsoft SQL Server con ONTAP 
---
= Recuperación ante desastres de Microsoft SQL Server con ONTAP
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Las bases de datos empresariales y las infraestructuras de aplicaciones a menudo requieren la replicación para protegerse de desastres naturales o de la interrupción inesperada del negocio con un tiempo de inactividad mínimo.

La característica de replicación de grupo de disponibilidad siempre disponible de SQL Server puede ser una excelente opción, y NetApp ofrece optiosn para integrar la protección de datos con Always-On. Sin embargo, en algunos casos es posible que desee considerar la tecnología de replicación de ONTAP. Las opciones de replicación de ONTAP, como MetroCluster y SnapMirror, pueden escalarse mejor con un impacto mínimo en el rendimiento, proteger los datos que no son de SQL y, en general, proporcionar una solución de replicación y recuperación ante desastres de toda la infraestructura.



== SnapMirror asíncrono

La tecnología SnapMirror ofrece una solución empresarial asíncrona, rápida y flexible para replicar datos en LAN y WAN. La tecnología SnapMirror solo transfiere los bloques de datos modificados al destino una vez que se creó el reflejo inicial, lo que reduce considerablemente los requisitos de ancho de banda de la red.

Las siguientes son recomendaciones para SnapMirror para SQL Server:

* Si se usa CIFS, la SVM de destino debe ser miembro del mismo dominio de Active Directory al que pertenece la SVM de origen para que las listas de control de acceso (ACL) almacenadas en archivos NAS no se interrumpan durante la recuperación de un desastre.
* No es necesario usar nombres de volúmenes de destino iguales a los nombres de los volúmenes de origen, pero puede simplificar la gestión del proceso de montaje de los volúmenes de destino en el destino. Si se utiliza CIFS, debe hacer que el espacio de nombres NAS de destino sea idéntico en rutas y la estructura de directorios para el espacio de nombres de origen.
* Con fines de coherencia, no programe actualizaciones de SnapMirror de las controladoras. En lugar de eso, habilite las actualizaciones de SnapMirror desde SnapCenter para actualizar SnapMirror después de haber completado el backup completo o de registro.
* Distribuya los volúmenes que contienen datos de SQL Server en diferentes nodos del clúster para permitir que todos los nodos del clúster compartan la actividad de replicación de SnapMirror. Esta distribución optimiza el uso de los recursos de los nodos.


Para obtener más información acerca de SnapMirror, consulte link:https://www.netapp.com/us/media/tr-4015.pdf["TR-4015: Guía de configuración de SnapMirror y prácticas recomendadas para ONTAP 9"^].
