---
sidebar: sidebar 
permalink: mssql/shared-vs-dedicated.html 
keywords: MS-SQL,mssql,SQL Server 
summary: Microsoft SQL Server en ONTAP 
---
= Instancia compartida de Microsoft SQL Server frente a instancia dedicada
:allow-uri-read: 


[role="lead"]
Si una aplicación tiene muchos esquemas y procedimientos almacenados, podría afectar a otras aplicaciones que comparten una instancia de SQL Server.

Los recursos de la instancia pueden estar potencialmente divididos o bloqueados, lo que a su vez provoca problemas de rendimiento para otras aplicaciones que tienen bases de datos alojadas en la instancia compartida de SQL Server.

La solución de problemas de rendimiento puede ser complicada porque debe averiguar qué instancia es la causa raíz. Esta pregunta se compara con los costes de las licencias del sistema operativo y de las licencias de SQL Server. Si el rendimiento de las aplicaciones es primordial, se recomienda encarecidamente utilizar una instancia dedicada.

Microsoft concede licencias de SQL Server por núcleo a nivel de servidor y no por instancia. Por este motivo, los administradores de bases de datos se ven tentados a instalar tantas instancias de SQL Server como el servidor pueda manejar para ahorrar en costes de licencias, lo que puede ocasionar mayores problemas de rendimiento más adelante.


TIP: *NetApp recomienda* elegir instancias dedicadas de SQL Server siempre que sea posible para obtener un rendimiento óptimo.
