---
sidebar: sidebar 
permalink: mssql/Storage-considerations.html 
keywords: MS-SQL,mssql,SQL Server, database layout 
summary: Microsoft SQL Server en ONTAP 
---
= Consideraciones sobre almacenamiento de Microsoft SQL Server
:allow-uri-read: 


[role="lead"]
La combinación de las soluciones de almacenamiento de NetApp y Microsoft SQL Server permite crear diseños de almacenamiento de base de datos de nivel empresarial que satisfacen los requisitos de aplicaciones más exigentes en la actualidad.

Para optimizar ambas tecnologías, es vital comprender el patrón y las características de E/S de SQL Server. Gracias a una buena distribución de almacenamiento para una base de datos de SQL Server, el rendimiento de SQL Server y la gestión de la infraestructura de SQL Server. Una buena distribución de almacenamiento también permite que la puesta en marcha inicial tenga éxito y que el entorno crezca sin problemas con el tiempo a medida que crece el negocio.



== Diseño de almacenamiento de datos

Para las bases de datos de SQL Server que no utilizan SnapCenter para realizar backups, Microsoft recomienda colocar los archivos de datos y de registro en unidades independientes. Para las aplicaciones que actualizan y solicitan datos simultáneamente, el archivo de registro tiene un gran consumo de escrituras y el archivo de datos (en función de la aplicación) tiene un gran volumen de lecturas y escrituras. Para la recuperación de datos, el archivo de registro no es necesario. Por lo tanto, las solicitudes de datos pueden satisfacerse desde el archivo de datos ubicado en su propia unidad.

Cuando se crea una nueva base de datos, Microsoft recomienda especificar unidades independientes para los datos y los registros. Para mover archivos después de crear la base de datos, ésta debe desconectarse. Para obtener más recomendaciones de Microsoft, consulte link:https://docs.microsoft.com/en-us/sql/relational-databases/policy-based-management/place-data-and-log-files-on-separate-drives?view=sql-server-ver15["Coloque los archivos de datos y de registro en unidades separadas"^].



== Agregados

Los agregados son los contenedores de almacenamiento principales para las configuraciones de almacenamiento de NetApp y contienen uno o varios grupos RAID compuestos tanto por discos de datos como por discos de paridad. NetApp ha realizado distintas pruebas de caracterización de las cargas de trabajo de I/O utilizando agregados compartidos y dedicados con archivos de datos y archivos de registro de transacciones separados. Las pruebas muestran que un gran agregado con más grupos RAID y discos optimiza y mejora el rendimiento del almacenamiento y que los administradores pueden gestionarlo con mayor facilidad por dos motivos:

* Un gran agregado pone a disposición de todos los archivos las funcionalidades I/O de todos los discos.
* Un agregado de gran tamaño permite hacer un uso más eficiente del espacio en disco.


Para alta disponibilidad (HA), colocar la réplica síncrona secundaria de SQL Server Always On Availability Group en una máquina virtual de almacenamiento (SVM) independiente del agregado. Para fines de recuperación ante desastres, coloque la réplica asíncrona en un agregado que forma parte de un clúster de almacenamiento separado en el sitio de recuperación ante desastres, con el contenido replicado mediante la tecnología SnapMirror de NetApp. NetApp recomienda tener al menos un 10% de espacio libre disponible en un agregado para un rendimiento del almacenamiento óptimo.



== Volúmenes

Los volúmenes NetApp FlexVol se crean y residen dentro de los agregados. Pueden crearse muchos volúmenes en un único agregado, y cada volumen puede ampliarse, reducirse o moverse entre agregados sin tiempo de inactividad del usuario.



=== Consideraciones sobre el diseño del volumen

Antes de crear un diseño de volumen de base de datos, es importante comprender cómo los patrones de I/O de SQL Server y las características varían en función de la carga de trabajo y de los requisitos de backup y recuperación. Consulte las siguientes recomendaciones de NetApp para volúmenes flexibles:

* Use volúmenes flexibles para almacenar archivos de base de datos de SQL Server y evite compartir volúmenes entre hosts.
* Utilice puntos de montaje NTFS en lugar de letras de unidad para superar la limitación de 26 unidades en Windows. Cuando se usan puntos de montaje de volumen, se recomienda generalmente asignar a la etiqueta de volumen el mismo nombre que el punto de montaje.
* Cuando sea necesario, configure una política de tamaño automático de volúmenes para ayudar a evitar condiciones de falta de espacio. 17 Guía de mejores prácticas para Microsoft SQL Server con ONTAP © 2022 NetApp, Inc. Todos los derechos reservados.
* Active la reubicación de lectura en el volumen cuando el perfil de E/S de la base de datos de SQL Server consta principalmente de lecturas secuenciales grandes, como con cargas de trabajo del sistema de soporte de decisiones. La reasignación de lectura optimiza los bloques para proporcionar un mejor rendimiento.
* Si instala SQL Server en un recurso compartido de SMB, asegúrese de que Unicode esté habilitado en los volúmenes SMB/CIFS para crear carpetas.
* Establezca el valor de reserva de la copia snapshot de NetApp en el volumen en cero para facilitar la supervisión desde un punto de vista operativo.
* Desactive los programas de copia y las políticas de retención de STORAGE Snapshot™. En su lugar, utilice SnapCenter para coordinar las copias Snapshot de los volúmenes de datos de SQL Server.
* Coloque las bases de datos del sistema SQL Server en un volumen o VMDK dedicado.
* Tempdb es una base de datos del sistema utilizada por SQL Server como espacio de trabajo temporal, especialmente para operaciones DBCC CHECKDB intensivas en E/S. Por lo tanto, coloque esta base de datos en un volumen dedicado con un conjunto de discos separado. En entornos grandes en los que el número de volúmenes es un reto, puede consolidar tempdb en menos volúmenes y almacenarlo en el mismo volumen que otras bases de datos del sistema tras una planificación cuidadosa. La protección de datos para tempdb no es una prioridad alta porque esta base de datos se vuelve a crear cada vez que se reinicia SQL Server.
* Coloque los archivos de datos de usuario (.mdf) en volúmenes independientes debido a que son cargas de trabajo de lectura/escritura aleatorias. Es común crear backups de registros de transacciones con más frecuencia que los backups de bases de datos. Por este motivo, coloque los archivos de registro de transacciones (.ldf) en un volumen o VMDK separados de los archivos de datos para poder crear programaciones de backup independientes para cada uno. Esta separación también aísla la E/S de escritura secuencial de los archivos de registro de la E/S de lectura/escritura aleatoria de los archivos de datos y mejora significativamente el rendimiento de SQL Server.




== LUN

* Asegúrese de que los archivos de la base de datos del usuario y el directorio de registro para almacenar backup de registros se encuentren en volúmenes independientes para evitar que la política de retención sobrescriba las snapshots cuando estas se usen con la tecnología SnapVault.
* Asegúrese de que las bases de datos de SQL Server residen en LUN independientes de los LUN que tienen archivos que no son de base de datos, como los archivos relacionados con búsqueda de texto completo.
* La colocación de archivos secundarios de base de datos (como parte de un grupo de archivos) en volúmenes distintos mejora el rendimiento de la base de datos de SQL Server. Esta separación solo es válida si el archivo .mdf de la base de datos no comparte su LUN con ningún otro archivo .mdf.
* Si crea LUN con DiskManager u otras herramientas, asegúrese de que el tamaño de unidad de asignación esté establecido en 64K para las particiones al formatear las LUN.
* Consulte link:https://www.netapp.com/media/10680-tr4080.pdf["Microsoft Windows e MPIO nativo bajo las prácticas recomendadas de ONTAP para SAN moderna"] Para aplicar la compatibilidad con accesos múltiples en Windows a dispositivos iSCSI en las propiedades MPIO.




=== Directorio de registro

El directorio de registro se especifica en SQL Server para almacenar datos de backup del registro de transacciones en el nivel de host. Si utiliza SnapCenter para realizar backup de archivos de registro, cada host SQL Server que utiliza SnapCenter debe tener un directorio de registro de host configurado para realizar backups de registros. SnapCenter tiene un repositorio de base de datos, por lo que los metadatos relacionados con las operaciones de backup, restauración o clonado se almacenan en un repositorio de base de datos central.

Los tamaños del directorio de registro de host se calculan de la siguiente manera:
Tamaño del directorio de registro de host = ( (tamaño máximo de LDF de base de datos x tasa de cambio de registro diario %) x (retención de instantánea) ÷ (1: Porcentaje de espacio de sobrecarga de LUN)
La fórmula de ajuste de tamaño del directorio de registro del host asume una sobrecarga del 10% de las LUN

Coloque el directorio de registro en un volumen o LUN dedicados. La cantidad de datos en el directorio de registro del host depende del tamaño de los backups y de la cantidad de días que se retienen los backups. SnapCenter solo permite un directorio de registro de host por cada host SQL Server. Puede configurar los directorios de registro de host en SnapCenter --> Host --> Configurar el plugin.

[TIP]
====
*NetApp recomienda* lo siguiente para un directorio de registro de host:

* Asegúrese de que el directorio de registro de host no esté compartido por ningún otro tipo de datos que pueda dañar los datos de la instantánea de backup.
* No coloque bases de datos de usuario ni bases de datos del sistema en un LUN que aloje puntos de montaje.
* Cree el directorio de registro de host en el volumen FlexVol dedicado al cual SnapCenter copia los registros de transacciones.
* Utilice los asistentes de SnapCenter para migrar bases de datos al almacenamiento NetApp de modo que las bases de datos se almacenen en ubicaciones válidas, lo que permite realizar correctamente las operaciones de backup y restauración de SnapCenter. Tenga en cuenta que el proceso de migración es disruptivo y puede provocar que las bases de datos se desconecten mientras se realiza la migración.
* Deben establecerse las siguientes condiciones para las instancias de clúster de conmutación por error (FCI) de SQL Server:
+
** Si va a utilizar una instancia de clúster de conmutación al nodo de respaldo, el LUN del directorio de registro de host debe ser un recurso de disco de clúster en el mismo grupo de clústeres que la instancia de SQL Server que se va a realizar el backup de SnapCenter.
** Si utiliza una instancia de clúster de conmutación al nodo de respaldo, las bases de datos de usuario deben colocarse en LUN compartidos que sean recursos de clúster de discos físicos asignados al grupo de clústeres asociado con la instancia de SQL Server.




====