---
sidebar: sidebar 
permalink: vmware/vmware-srm-overview.html 
keywords: ontap, vsphere, srm, srm, hybrid, cloud, migration, vmware, site, recovery manager, vsrm,VLSR 
summary: 'La solución ONTAP para la recuperación de sitios en directo (VLSR) y el administrador de recuperación de sitios (SRM) de VMware' 
---
= Recuperación de sitios en vivo de VMware con ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP ha servido como solución de almacenamiento líder para VMware vSphere y, más recientemente, entornos de Cloud Foundation desde su introducción en el centro de datos moderno en 2002. Sigue introduciendo funciones innovadoras que simplifican la gestión y reducen los costes.

Este documento presenta la solución ONTAP para Live Site Recovery (VLSR) de VMware, anteriormente conocido como Site Recovery Manager (SRM), el software de recuperación ante desastres (DR) líder en el sector de VMware, incluyendo la información de productos más reciente y las mejores prácticas para optimizar la implementación, reducir el riesgo y simplificar la gestión continua.


NOTE: Esta documentación sustituye al informe técnico _TR-4900 publicado anteriormente: VMware Site Recovery Manager por ONTAP_

Las prácticas recomendadas complementan otros documentos como guías y herramientas de compatibilidad. Se desarrollan según pruebas de laboratorio y una amplia experiencia de campo por parte de ingenieros y clientes de NetApp. En algunos casos, las prácticas recomendadas pueden no ser la opción adecuada para su entorno; sin embargo, generalmente son las soluciones más sencillas que satisfacen las necesidades del mayor número de clientes.

Este documento se centra en las funcionalidades de los últimos lanzamientos de ONTAP 9 cuando se utiliza junto con las herramientas de ONTAP para VMware vSphere 10,4 (que incluye el adaptador de replicación del almacenamiento de NetApp [SRA] y el proveedor VASA [VP]), así como la recuperación de sitio en activo de VMware 9.



== ¿Por qué usar ONTAP con VLSR o SRM?

Las plataformas de gestión de datos NetApp de ONTAP son algunas de las soluciones de almacenamiento para VLSR más adoptadas. Las razones están en abundancia: Una plataforma de gestión de datos de protocolo unificado seguro y de alto rendimiento (NAS y SAN juntos) que proporcione eficiencia del almacenamiento que defina el sector, multi-tenancy, controles de calidad de servicio, protección de datos con copias Snapshot con gestión eficiente del espacio y replicación con SnapMirror. Todos ellos aprovechan la integración nativa en el multicloud híbrido para la protección de las cargas de trabajo de VMware y una gran cantidad de herramientas de automatización y orquestación a su alcance.

Al utilizar SnapMirror para la replicación basada en cabina, aprovecha una de las tecnologías más contrastadas y maduras de ONTAP. SnapMirror le ofrece la ventaja de las transferencias de datos seguras y altamente eficientes, con la copia solo de los bloques del sistema de archivos modificados, no de máquinas virtuales completas ni de almacenes de datos. Incluso esos bloques aprovechan el ahorro de espacio, como la deduplicación, la compresión y la compactación. Los sistemas ONTAP modernos ahora utilizan SnapMirror sin versiones, lo que le ofrece la flexibilidad de seleccionar sus clústeres de origen y destino. SnapMirror se ha convertido en una de las herramientas más potentes disponibles para la recuperación ante desastres.

Tanto si se utilizan almacenes de datos tradicionales NFS, iSCSI o conectados a Fibre Channel (ahora con compatibilidad con almacenes de datos vVols), VLSR ofrece una sólida oferta de primera parte que aprovecha las mejores funcionalidades de ONTAP para la planificación y orquestación de la recuperación ante desastres o de la migración al centro de datos.



== Aprovechamiento de VLSR ONTAP 9

VLSR aprovecha las tecnologías avanzadas de gestión de datos de los sistemas de ONTAP al integrarse con herramientas de ONTAP para VMware vSphere, un dispositivo virtual que incluye tres componentes principales:

* El complemento de herramientas de ONTAP para vCenter, anteriormente conocido como consola de almacenamiento virtual (VSC), simplifica las funciones de eficiencia y gestión del almacenamiento, mejora la disponibilidad y reduce los costes de almacenamiento y la sobrecarga operativa, tanto si utiliza SAN como NAS. Utiliza prácticas recomendadas para aprovisionar almacenes de datos y optimiza la configuración de host ESXi para entornos de almacenamiento en bloques y NFS. Para obtener todos estos beneficios, NetApp recomienda este plugin cuando se utiliza vSphere con sistemas que ejecutan ONTAP.
* Las herramientas de ONTAP VASA Provider admiten las API de VMware vStorage para el marco de conocimiento del almacenamiento (VASA). EL proveedor DE VASA conecta vCenter Server con ONTAP para ayudar en el aprovisionamiento y la supervisión del almacenamiento de máquinas virtuales. Esto ha permitido el soporte de VMware Virtual Volumes (vVols) y la gestión de políticas de almacenamiento de VM y el rendimiento de vVols individuales de VM. También proporciona alarmas para controlar la capacidad y el cumplimiento de los perfiles.
* El SRA se usa junto con el VLSR para gestionar la replicación de datos de máquinas virtuales entre sitios de producción y recuperación ante desastres para almacenes de datos VMFS tradicionales y NFS, y también para las pruebas no disruptivas de réplicas de recuperación ante desastres. Ayuda a automatizar las tareas de identificación, recuperación y protección. Incluye tanto un dispositivo de servidor SRA como adaptadores SRA para el servidor SRM de Windows y el dispositivo VLSR.


Después de instalar y configurar los adaptadores de SRA en el servidor VLSR para proteger almacenes de datos que no son vVols, puede comenzar la tarea de configurar el entorno de vSphere para la recuperación ante desastres.

El SRA proporciona una interfaz de comando y control para que el servidor VLSR gestione los volúmenes de ONTAP FlexVol que contienen las máquinas virtuales de VMware (VM), además de la replicación de SnapMirror que las protege.

VLSR puede probar su plan de recuperación ante desastres sin interrupciones con la tecnología FlexClone de NetApp para crear clones casi instantáneos de los almacenes de datos protegidos del centro de recuperación ante desastres. VLSR crea una zona aislada para probar con seguridad de modo que su organización y sus clientes estén protegidos en caso de un verdadero desastre, lo que le da confianza en que sus organizaciones pueden ejecutar una conmutación por error durante un desastre.

En caso de verdadero desastre o incluso de una migración planificada, VLSR permite enviar cualquier cambio de última hora al conjunto de datos mediante una actualización final de SnapMirror (si lo decide). A continuación, interrumpe el reflejo y monta el almacén de datos en los hosts de recuperación ante desastres. En ese momento, las máquinas virtuales pueden encenderse automáticamente en cualquier orden de acuerdo con la estrategia planificada previamente.


NOTE: Aunque los sistemas ONTAP le permitirán emparejar SVM en el mismo clúster para la replicación de SnapMirror, ese escenario no se ha probado ni certificado con VLSR. Por lo tanto, se recomienda usar solo SVM de diferentes clústeres cuando se utilice VLSR.



== VLSR con ONTAP y otros casos de uso: Cloud híbrido y migración

La integración de su puesta en marcha de VLSR con las capacidades de gestión de datos avanzadas de ONTAP posibilita una ampliación y un rendimiento mucho mejores en comparación con las opciones de almacenamiento local. Mucho más que eso, aporta la flexibilidad del cloud híbrido. El cloud híbrido le permite ahorrar dinero al organizar en niveles los bloques de datos no utilizados de su cabina de alto rendimiento en su proveedor a hiperescala preferido mediante FabricPool, que podría ser un almacén de S3 en las instalaciones, como StorageGRID de NetApp. También puede utilizar SnapMirror para sistemas basados en periféricos con ONTAP Select definido por software o DR basada en cloud utilizando Cloud Volumes ONTAP (CVO) u https://www.equinix.com/partners/netapp["Almacenamiento NetApp en Equinix Metal®"^] otros servicios ONTAP alojados.

Podría entonces hacer una conmutación por error de prueba dentro del centro de datos de un proveedor de servicios en cloud con un espacio de almacenamiento prácticamente nulo gracias a FlexClone. La protección de su empresa ahora puede costar menos que nunca.

VLSR también puede utilizarse para ejecutar migraciones planificadas aprovechando SnapMirror para transferir de forma eficiente sus máquinas virtuales desde un centro de datos a otro o incluso dentro del mismo centro de datos, ya sea el suyo o mediante cualquier otro proveedor de servicios para partners de NetApp.
