---
sidebar: sidebar 
permalink: vmware/vmware-srm-ontap-tools-features.html 
keywords: vmware, site, recovery manager, vsrm, vsphere, ipv6, support, rest, api, replication, ccols, spbm, srm, appliance based 
summary: Soporte para funciones, límites y vVols con las herramientas de ONTAP. 
---
= Nuevas funcionalidades con VLSR/SRM y ONTAP Tools
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Con la transición del dispositivo virtual anterior, las herramientas de ONTAP incorporan una gran cantidad de nuevas funciones, límites más altos y nueva compatibilidad con vVols.



== Versiones más recientes de vSphere y Site Recovery Manager

NetApp ha compartido una estrecha colaboración con VMware durante casi dos décadas y se esfuerza por ofrecer soporte para las últimas versiones de Lo antes posible.. Compruebe siempre en NetApp https://mysupport.netapp.com/matrix/imt.jsp?components=84943;&solution=1777&isHWU&src=IMT["Herramienta de matriz de interoperabilidad (IMT)"^] las combinaciones cualificadas más recientes de software.



== Compatibilidad con IPv6

IPv6 ahora es compatible con las siguientes limitaciones:

* No es compatible con SRM 8.2 (8.1, 8.3 y 8. 4 y versiones posteriores)
* Consulte la https://mysupport.netapp.com/matrix/imt.jsp?components=84943;&solution=1777&isHWU&src=IMT["Herramienta de matriz de interoperabilidad (IMT)"^] para obtener las últimas versiones cualificadas.




== Mayor escala

Las herramientas de ONTAP 10,4 SRA ahora pueden admitir la escala máxima de VLSR/SRM.

* Cantidad total de máquinas virtuales protegidas = 5000
* Número de equipos virtuales por grupo de protección = 1000
* Número total de planes de recuperación = 250
* Número total de grupos de protección por plan de recuperación = 250
* Número total de almacenes de datos replicados = 255
* Núm. Total de planes de recuperación en ejecución simultánea. = 10




== Replicación síncrona

Una nueva función que se espera tanto y que se prevé que será SnapMirror Synchronous (SM-S) con ONTAP 9.5 y posterior, que ofrece una solución de replicación de datos de RPO cero para sus aplicaciones críticas. SM-S requiere las herramientas ONTAP 9.8 o posterior.



== Soporte para API de REST

La configuración del servidor SRA ahora puede gestionarse mediante API DE REST. Se ha agregado una interfaz de usuario de Swagger para ayudarle a crear sus flujos de trabajo de automatización y puede encontrarse en el dispositivo de herramientas de ONTAP en `https://<appliance>:8443/`.
