---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-why.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: Los clientes seleccionan ONTAP para vSphere con confianza debido a sus soluciones de almacenamiento SAN y NAS unificadas y a la nueva arquitectura de almacenamiento desagregado simplificada, que se incluye en las cabinas All SAN más recientes. Esta plataforma ofrece una protección Snapshot excepcional y sólidas herramientas de gestión. Mediante la descarga de funciones en un almacenamiento dedicado, ONTAP maximiza los recursos del host, reduce los costes y mantiene un rendimiento óptimo. Además, las cargas de trabajo pueden migrarse fácilmente mediante Storage vMotion en VMFS, NFS o vVols. 
---
= ¿Por qué elegir ONTAP para VMware vSphere?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Los clientes eligen con confianza ONTAP for vSphere para soluciones de almacenamiento SAN y NAS.  La nueva arquitectura de almacenamiento desagregado simplificada, que se incluye en las últimas matrices All SAN, ofrece una experiencia simplificada familiar para los administradores de almacenamiento SAN y, al mismo tiempo, conserva la mayoría de las integraciones y el conjunto de características de los sistemas ONTAP tradicionales.  Los sistemas ONTAP proporcionan una protección excepcional de instantáneas y herramientas de gestión sólidas.  Al descargar funciones al almacenamiento dedicado, ONTAP maximiza los recursos del host, reduce costos y mantiene un rendimiento óptimo.  Además, las cargas de trabajo se pueden migrar fácilmente mediante Storage vMotion a través de VMFS, NFS o vVols.



== Las ventajas de usar ONTAP para vSphere

Hay muchas razones por las que decenas de miles de clientes han seleccionado ONTAP como solución de almacenamiento para vSphere, como un sistema de almacenamiento unificado que admite los protocolos SAN y NAS, sólidas funcionalidades de protección de datos mediante copias Snapshot con gestión eficiente del espacio y una gran cantidad de herramientas para ayudarle a gestionar los datos de aplicaciones. El uso de un sistema de almacenamiento independiente del hipervisor permite descargar numerosas funciones y maximizar su inversión en sistemas de host vSphere. Este método no solo garantiza que los recursos del host se centren en las cargas de trabajo de las aplicaciones, sino que también evita efectos de rendimiento aleatorios en las aplicaciones de operaciones de almacenamiento.

El uso de ONTAP junto con vSphere es una excelente combinación que le permite reducir los gastos de hardware del host y software VMware.  También puede proteger sus datos a un menor coste y con un alto rendimiento constante.  Debido a que las cargas de trabajo virtualizadas son móviles, puede explorar diferentes enfoques usando Storage vMotion para mover máquinas virtuales entre almacenes de datos VMFS, NFS o vVols , todo en el mismo sistema de almacenamiento.

Estos son los factores clave que los clientes valoran hoy en día:

* *Almacenamiento unificado.*  Los sistemas que ejecutan ONTAP están unificados de varias maneras importantes.  Originalmente, este enfoque se refería a los protocolos NAS y SAN, y ONTAP continúa siendo una plataforma líder para SAN, junto con su fortaleza original en NAS.  En el mundo vSphere, este enfoque también podría significar un sistema unificado para la infraestructura de escritorio virtual (VDI) junto con la infraestructura de servidor virtual (VSI).  Los sistemas que ejecutan ONTAP suelen ser menos costosos para VSI que las matrices empresariales tradicionales y, además, tienen capacidades avanzadas de eficiencia de almacenamiento para manejar VDI en el mismo sistema.  ONTAP también unifica una variedad de medios de almacenamiento, desde SSD hasta SATA, y puede extenderlo fácilmente a la nube.  No es necesario comprar un sistema operativo de almacenamiento para el rendimiento, otro para los archivos y otro más para la nube.  ONTAP los une a todos.
* *Cabina All SAN (ASA).* Los sistemas de ONTAP ASA más recientes (a partir de A1K, A90, A70, A50, A30 y A20) se basan en una nueva arquitectura de almacenamiento que elimina el paradigma de almacenamiento tradicional de ONTAP relativo a la gestión de agregados y volúmenes. Como no hay recursos compartidos del sistema de archivos, no se necesitan volúmenes. Todo el almacenamiento conectado a un par de alta disponibilidad se trata como una zona de disponibilidad de almacenamiento común (SAZ) dentro de la que los LUN y los espacios de nombres de NVMe se aprovisionan como «unidades de almacenamiento» (SUS). Los últimos sistemas ASA han sido diseñados para ser fáciles de gestionar, gracias a una experiencia familiar para los administradores de almacenamiento SAN. Esta nueva arquitectura es ideal para entornos de vSphere, ya que permite una gestión sencilla de los recursos de almacenamiento y ofrece una experiencia simplificada para los administradores de almacenamiento SAN. La arquitectura de ASA también es compatible con la tecnología NVMe over Fabrics (NVMe-oF) más reciente, que proporciona un rendimiento y una escalabilidad aún mayores para las cargas de trabajo de vSphere.
* *Tecnología Snapshot.* ONTAP fue el primero en ofrecer tecnología Snapshot para la protección de datos y sigue siendo la más avanzada en el sector. Este método de protección de datos con un uso eficiente del espacio se ha ampliado para dar soporte a las API de VMware vSphere para la integración de cabinas (VAAI). Esta integración le permite aprovechar las capacidades Snapshot de ONTAP en las operaciones de backup y restauración, y reducir el impacto en su entorno de producción. Este método también permite utilizar copias Snapshot para una rápida recuperación de equipos virtuales, lo que reduce el tiempo y el esfuerzo necesarios para restaurar datos. Además, la tecnología Snapshot de ONTAP se integra con las soluciones Live Site Recovery (VLSR, anteriormente Site Recovery Manager [SRM]) de VMware, por lo que proporciona una estrategia de protección de datos completa para su entorno virtualizado.
* *Volúmenes virtuales y gestión de almacenamiento basada en políticas.*  NetApp fue uno de los primeros socios de diseño de VMware en el desarrollo de vSphere Virtual Volumes (vVols), aportando información arquitectónica y soporte temprano para vVols y VMware vSphere API for Storage Awareness (VASA).  Este enfoque no solo aportó una gestión granular del almacenamiento de máquinas virtuales a VMFS, sino que también respaldó la automatización del aprovisionamiento de almacenamiento a través de una gestión de almacenamiento basada en políticas.  Este enfoque permite a los arquitectos de almacenamiento diseñar grupos de almacenamiento con diferentes capacidades que los administradores de máquinas virtuales pueden utilizar fácilmente.  ONTAP lidera la industria del almacenamiento en escala vVol, y admite cientos de miles de vVols en un solo clúster, mientras que los proveedores de matrices empresariales y matrices flash más pequeñas admiten tan solo varios miles de vVols por matriz.  NetApp también está impulsando la evolución de la gestión granular de máquinas virtuales con sus próximas capacidades.
* *Eficiencia de almacenamiento.*  Si bien NetApp fue el primero en ofrecer deduplicación para cargas de trabajo de producción, esta innovación no fue la primera ni la última en esta área.  Todo comenzó con instantáneas, un mecanismo de protección de datos que ahorra espacio y no afecta el rendimiento, junto con la tecnología FlexClone para hacer instantáneamente copias de lectura y escritura de máquinas virtuales para uso en producción y respaldo.  NetApp continuó ofreciendo capacidades en línea, incluidas deduplicación, compresión y deduplicación de bloque cero, para aprovechar al máximo el almacenamiento de los costosos SSD.  ONTAP también agregó la capacidad de empaquetar operaciones de E/S y archivos más pequeños en un bloque de disco usando compactación.  La combinación de estas capacidades ha permitido que los clientes experimenten comúnmente ahorros de hasta 5:1 para VSI y hasta 30:1 para VDI.  La última generación de sistemas ONTAP también incluye compresión y deduplicación aceleradas por hardware, lo que puede mejorar aún más la eficiencia del almacenamiento y reducir los costos.  Este enfoque permite almacenar más datos en menos espacio, lo que reduce el costo general de almacenamiento y mejora el rendimiento.  NetApp confía tanto en sus capacidades de eficiencia de almacenamiento que ofrece un enlace: https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf [Garantía de eficiencia^].
* *Multitenencia.*  ONTAP ha sido durante mucho tiempo líder en multitenencia, lo que le permite crear múltiples máquinas virtuales de almacenamiento (SVM) en un solo clúster.  Este enfoque le permite aislar cargas de trabajo y brindar diferentes niveles de servicio a diferentes inquilinos, lo que lo hace ideal para proveedores de servicios y grandes empresas.  La última generación de sistemas ONTAP también incluye soporte para la gestión de la capacidad de los inquilinos.  Esta función le permite establecer límites de capacidad para cada inquilino, garantizando que ningún inquilino pueda consumir todos los recursos disponibles.  Este enfoque ayuda a garantizar que todos los inquilinos reciban el nivel de servicio que esperan, al tiempo que proporciona un alto nivel de seguridad y aislamiento entre ellos.  Además, las capacidades multitenencia de ONTAP están integradas con la plataforma vSphere de VMware, lo que le permite administrar y monitorear fácilmente su entorno virtualizado a través de https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["Herramientas de ONTAP para VMware vSphere"] y https://docs.netapp.com/us-en/data-infrastructure-insights/["Información sobre la infraestructura de datos"] .
* *Nube híbrida.*  Ya sea que se utilicen para una nube privada local, una infraestructura de nube pública o una nube híbrida que combina lo mejor de ambas, las soluciones ONTAP lo ayudan a construir su estructura de datos para agilizar y optimizar la administración de datos.  Comience con sistemas all-flash de alto rendimiento y luego combínelos con sistemas de almacenamiento en disco o en la nube para la protección de datos y la computación en la nube.  Elija entre Azure, AWS, IBM o Google Cloud para optimizar costos y evitar la dependencia. Aproveche el soporte avanzado para OpenStack y tecnologías de contenedores según sea necesario.  NetApp también ofrece copias de seguridad basadas en la nube (SnapMirror Cloud, Cloud Backup Service y Cloud Sync) y herramientas de archivado y niveles de almacenamiento (FabricPool) para ONTAP para ayudar a reducir los gastos operativos y aprovechar el amplio alcance de la nube.
* *Y mucho más.* saque partido del rendimiento extremo de las cabinas AFF A-Series de NetApp para acelerar su infraestructura virtualizada a la vez que gestiona los costes. Disfrute de operaciones no disruptivas, desde el mantenimiento hasta las actualizaciones, pasando por la sustitución completa de su sistema de almacenamiento, mediante clústeres ONTAP de escalado horizontal. Proteja los datos en reposo con funcionalidades de cifrado de NetApp sin coste adicional. Asegúrese de que el rendimiento cumple los niveles de servicio empresarial a través de funcionalidades de calidad de servicio de gran precisión. Todos ellos forman parte de la amplia gama de funcionalidades que incluyen ONTAP, el software para la gestión de datos empresariales líder del sector.

