---
sidebar: sidebar 
permalink: vmware/vmware-srm-vvol-troubleshooting.html 
keywords: vmware, site, recovery manager, vlsr, hybrid, cloud, srm, vvols, replication 
summary: La replicación de vVols con VASA ofrece una funcionalidad única comparada con el SRA y los almacenes de datos tradicionales. 
---
= Solución de problemas de VLSRM/SRM cuando se usa la replicación de vVols
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cuando se utilizan las herramientas de ONTAP 9.13P2, el flujo de trabajo que hay en VLSR y SRM es muy diferente cuando se usa la replicación vVols de lo que se utiliza con el SRA y los almacenes de datos tradicionales. Por ejemplo, no hay ningún concepto de administrador de cabinas. Como tal, `discoverarrays` y `discoverdevices` los comandos nunca se ven.

Para la solución de problemas, resulta beneficioso comprender los nuevos flujos de trabajo, que se enumeran a continuación:

. QueryReplicationPeer: Descubre los acuerdos de replicación entre dos dominios de fallo.
. QueryFaultDomain: Detecta la jerarquía de dominios de fallo.
. QueryReplicationGroup: Detecta los grupos de replicación presentes en los dominios de origen o destino.
. SyncReplicationGroup: Sincroniza los datos entre el origen y el destino.
. QueryPointInTimeReplica: Detecta las réplicas de punto en tiempo en un destino.
. TestFailoverReplicationGroupStart: Inicia la conmutación por error de prueba.
. TestFailoverReplicationGroupStop: Finaliza la conmutación por error de prueba.
. PromoteReplicationGroup: Promueve un grupo actualmente en pruebas a la producción.
. PapreFailoverReplicationGroup: Prepara para una recuperación ante desastres.
. FailoverReplicationGroup: Ejecuta la recuperación ante desastres.
. ReverseReplicateGroup: Inicia la replicación inversa.
. QueryMatchingContainer: Busca contenedores (junto con hosts o grupos de replicación) que puedan satisfacer una solicitud de aprovisionamiento con una directiva determinada.
. QueryResourceMetadata: Descubre los metadatos de todos los recursos del proveedor VASA, la utilización de recursos puede devolverse como respuesta a la función queryMatchingContainer.


El error más común que se produce al configurar la replicación de vVols es no descubrir las relaciones de SnapMirror. Esto ocurre porque los volúmenes y las relaciones de SnapMirror se crean fuera del alcance de las herramientas de ONTAP. Por lo tanto, una práctica recomendada es asegurarse de que su relación con SnapMirror esté completamente inicializada y de que ha ejecutado una nueva detección en las herramientas de ONTAP en ambos sitios antes de intentar crear un almacén de datos vVols replicado.
