---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-overview.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: El software ONTAP de NetApp lleva casi dos décadas siendo una solución de almacenamiento líder para entornos VMware vSphere y sigue agregando funcionalidades innovadoras que simplifican la gestión y reducen los costes. Este documento presenta la solución ONTAP para vSphere, e incluye la información de producto más reciente y las prácticas recomendadas para simplificar la puesta en marcha, reducir el riesgo y simplificar la gestión. 
---
= VMware vSphere con ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El software ONTAP de NetApp lleva casi dos décadas siendo una solución de almacenamiento líder para entornos VMware vSphere y sigue agregando funcionalidades innovadoras que simplifican la gestión y reducen los costes. Este documento presenta la solución ONTAP para vSphere, e incluye la información de producto más reciente y las prácticas recomendadas para simplificar la puesta en marcha, reducir el riesgo y simplificar la gestión.


NOTE: Esta documentación sustituye a los informes técnicos publicados anteriormente _TR-4597: VMware vSphere para ONTAP_

Las prácticas recomendadas complementan otros documentos, como guías y listas de compatibilidad. Se desarrollan según pruebas de laboratorio y una amplia experiencia de campo por parte de ingenieros y clientes de NetApp. Puede que no sean las únicas prácticas compatibles que funcionan en todos los entornos, pero suelen ser las soluciones más sencillas que satisfacen las necesidades de la mayoría de los clientes.

Este documento se centra en las funcionalidades de los lanzamientos recientes de ONTAP (9.x) ejecutados en vSphere 7,0 o posterior. Consulte https://imt.netapp.com/matrix/#search["Herramienta de matriz de interoperabilidad de NetApp"^] y.. https://www.vmware.com/resources/compatibility/search.php?deviceCategory=san["Guía de compatibilidad de VMware"^] para obtener detalles relacionados con versiones específicas.



== ¿Por qué elegir ONTAP para vSphere?

Hay muchas razones por las que decenas de miles de clientes han seleccionado ONTAP como solución de almacenamiento para vSphere, como un sistema de almacenamiento unificado que admite los protocolos SAN y NAS, sólidas funcionalidades de protección de datos mediante copias Snapshot con gestión eficiente del espacio y una gran cantidad de herramientas para ayudarle a gestionar los datos de aplicaciones. El uso de un sistema de almacenamiento independiente del hipervisor permite descargar numerosas funciones y maximizar su inversión en sistemas de host vSphere. Este método no solo garantiza que los recursos del host se centren en las cargas de trabajo de las aplicaciones, sino que también evita efectos de rendimiento aleatorios en las aplicaciones de operaciones de almacenamiento.

El uso de ONTAP junto con vSphere es una excelente combinación que le permite reducir los gastos en hardware del host y software de VMware. También puede proteger sus datos con un coste menor y un alto rendimiento constante. Dado que las cargas de trabajo virtualizadas son móviles, puede explorar distintos enfoques mediante Storage vMotion para mover equipos virtuales entre almacenes de datos de VMFS, NFS o vVols, todo ello en el mismo sistema de almacenamiento.

Estos son algunos de los factores clave que valoran los clientes en la actualidad:

* *Almacenamiento unificado.* los sistemas que ejecutan el software ONTAP están unificados de varias maneras significativas. En un principio, este enfoque hacía referencia a los protocolos NAS y SAN, y ONTAP sigue siendo la plataforma líder para SAN junto con su fortaleza original en NAS. En el mundo de vSphere, este enfoque también podría significar un sistema unificado para una infraestructura de puestos de trabajo virtuales (VDI) junto con una infraestructura de servidores virtuales (VSI). Los sistemas que ejecutan el software ONTAP suelen ser menos caros para VSI que las cabinas empresariales tradicionales y, al mismo tiempo, cuentan con funcionalidades avanzadas de eficiencia del almacenamiento para manejar VDI en el mismo sistema. ONTAP también unifica varios medios de almacenamiento, desde SSD a SATA, y puede ampliarlos fácilmente al cloud. No es necesario comprar una cabina flash para el rendimiento, una cabina SATA para archivos y sistemas independientes para la nube. ONTAP los une a todos.
* *Gestión basada en políticas de almacenamiento y volúmenes virtuales* NetApp fue un socio de diseño temprano con VMware en el desarrollo de vSphere Virtual Volumes (vVols), proporcionando información arquitectónica y soporte temprano para vVols y VMware vSphere APIs for Storage Awareness (Vasa). Este enfoque no solo integró la gestión granular de almacenamiento de máquinas virtuales en VMFS, sino que también admitió la automatización del aprovisionamiento de almacenamiento a través de la gestión basada en políticas de almacenamiento. Este enfoque permite a los arquitectos de almacenamiento diseñar pools de almacenamiento con distintas funcionalidades que pueden consumir fácilmente los administradores de máquinas virtuales. ONTAP es líder en el sector del almacenamiento a escala VVol, por lo que admite cientos de miles de vVols en un único clúster, mientras que las cabinas empresariales y los proveedores de cabinas flash más pequeños admiten hasta varios miles de vVols por cabina. NetApp también está impulsando la evolución de la gestión granular de equipos virtuales con próximas funcionalidades para admitir vVols 3.0.
* *Eficiencia del almacenamiento*. Aunque NetApp fue el primero en ofrecer deduplicación para las cargas de trabajo de producción, esta innovación no fue la primera ni la última en esta área. Comenzó con copias Snapshot, un mecanismo de protección de datos con gestión eficiente del espacio sin efecto en el rendimiento, junto con la tecnología FlexClone para realizar de forma instantánea copias de lectura y escritura de equipos virtuales para producción y uso del backup. NetApp siguió ofreciendo funcionalidades inline, que incluían deduplicación, compresión y deduplicación de bloque cero, para sacar el máximo partido de almacenamiento de SSD de elevado coste. Más recientemente, ONTAP añadió la capacidad de empaquetar las operaciones de I/o y archivos más pequeños en un bloque de discos mediante la compactación. La combinación de estas funcionalidades ha dado como resultado que los clientes observan un ahorro de hasta 5:1 para VSI y de hasta 30:1 para la infraestructura de puestos de trabajo virtuales.
* *Cloud híbrido.* tanto si se utiliza para un cloud privado en las instalaciones, una infraestructura de cloud público o un cloud híbrido que combina lo mejor de ambos, las soluciones ONTAP le ayudan a crear su Data Fabric para optimizar y optimizar la gestión de datos. Empiece con sistemas all-flash de alto rendimiento y, a continuación, apítelos con sistemas de disco o de almacenamiento en cloud para protección de datos y cloud computing. Elija entre clouds de Azure, AWS, IBM o Google para optimizar costes y evitar la restricción. Aproveche el soporte avanzado para OpenStack y las tecnologías de contenedor según sea necesario. NetApp también ofrece backup basado en cloud (SnapMirror Cloud, Cloud Backup Service y Cloud Sync) y herramientas de organización en niveles del almacenamiento y archivado (FabricPool) para ONTAP para ayudar a reducir los gastos operativos y aprovechar el amplio alcance del cloud.
* *Y mucho más.* saque partido del rendimiento extremo de las cabinas AFF A-Series de NetApp para acelerar su infraestructura virtualizada a la vez que gestiona los costes. Disfrute de operaciones no disruptivas, desde el mantenimiento hasta las actualizaciones, pasando por la sustitución completa de su sistema de almacenamiento, mediante clústeres ONTAP de escalado horizontal. Proteja los datos en reposo con funcionalidades de cifrado de NetApp sin coste adicional. Asegúrese de que el rendimiento cumple los niveles de servicio empresarial a través de funcionalidades de calidad de servicio de gran precisión. Todos ellos forman parte de la amplia gama de funcionalidades que incluyen ONTAP, el software para la gestión de datos empresariales líder del sector.

