---
sidebar: sidebar 
permalink: vmware/vmware-security-tools.html 
keywords: wp-7353, wp7353, 7353, security, vmware, vsphere, Tools 
summary: En este documento se trata la seguridad de productos de las herramientas de ONTAP para VMware vSphere. 
---
= Herramientas de ONTAP para VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El departamento de ingeniería de software con herramientas de ONTAP de NetApp para VMware vSphere realiza las siguientes actividades de desarrollo seguro:

* *Modelado de amenazas.* el propósito del modelado de amenazas es descubrir defectos de seguridad en una característica, componente o producto al principio del ciclo de vida del desarrollo del software. Un modelo de amenaza es una representación estructurada de toda la información que afecta la seguridad de una aplicación. En esencia, es una visión de la aplicación y su entorno a través del objetivo de la seguridad.
* *Pruebas de seguridad de aplicaciones dinámicas (DAST).* esta tecnología está diseñada para detectar condiciones vulnerables en aplicaciones en su estado de funcionamiento. DAST prueba las interfaces HTTP y HTML expuestas de las aplicaciones web.
* *Moneda de código de terceros.* como parte del desarrollo de software con software de código abierto (OSS), debe tratar las vulnerabilidades de seguridad que pueden estar asociadas con cualquier OSS incorporado en su producto. Esto es un esfuerzo continuo porque una nueva versión de OSS podría tener una vulnerabilidad recién descubierta reportada en cualquier momento.
* *Análisis de vulnerabilidades.* el propósito del análisis de vulnerabilidades es detectar vulnerabilidades de seguridad comunes y conocidas en los productos de NetApp antes de que se lancen a los clientes.
* * Pruebas de penetración.* la prueba de penetración es el proceso de evaluar un sistema, una aplicación web o una red para encontrar vulnerabilidades de seguridad que podrían ser explotadas por un atacante. Las pruebas de penetración (pruebas de Pen) en NetApp las realiza un grupo de empresas de terceros aprobadas y fiables. Su alcance de prueba incluye el lanzamiento de ataques contra una aplicación o software similar a intrusos hostiles o piratas informáticos que utilizan métodos o herramientas de explotación sofisticados.




== Funciones de seguridad de los productos

Las herramientas de NetApp ONTAP para VMware vSphere incluyen las siguientes funciones de seguridad en cada versión.

* *Banner de inicio de sesión.* SSH está desactivado de forma predeterminada y sólo permite inicios de sesión de una vez si está activado desde la consola de VM. Se muestra el siguiente banner de inicio de sesión una vez que el usuario introduce un nombre de usuario en la solicitud de inicio de sesión:
+
*ADVERTENCIA:* el acceso no autorizado a este sistema está prohibido y será procesado por ley. Al acceder a este sistema, acepta que sus acciones pueden supervisarse si se sospecha un uso no autorizado.

+
Una vez que el usuario complete el inicio de sesión a través del canal SSH, se muestra el siguiente texto:



....
Linux vsc1 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
....
* *Control de acceso basado en roles (RBAC).* dos tipos de controles RBAC están asociados con las herramientas ONTAP:
+
** Privilegios nativos de vCenter Server
** Privilegios específicos del plugin de vCenter. Para obtener más información, consulte https://docs.netapp.com/vapp-98/topic/com.netapp.doc.vsc-dsg/GUID-4DCAD72F-34C9-4345-A7AB-A118F4DB9D4D.html["este enlace"^].


* *Canales de comunicaciones cifrados.* toda comunicación externa ocurre a través de HTTPS utilizando la versión 1.2 de TLS.
* *Exposición mínima del puerto.* sólo los puertos necesarios están abiertos en el firewall.
+
En la siguiente tabla se describen los detalles de los puertos abiertos.



|===
| Puerto TCP v4/v6 # | Dirección | Función 


| 8143 | entrante | Conexiones HTTPS para la API de REST 


| 8043 | entrante | Conexiones HTTPS 


| 9060 | entrante | Conexiones HTTPS
Se utiliza para conexiones SOAP a través de https
Este puerto se debe abrir para permitir que un cliente se conecte al servidor API de herramientas de ONTAP. 


| 22 | entrante | SSH (deshabilitado de forma predeterminada) 


| 9080 | entrante | Conexiones HTTPS - VP y SRA - conexiones internas sólo del bucle invertido 


| 9083 | entrante | Conexiones HTTPS: VP y SRA
Se utiliza para conexiones SOAP a través de https 


| 1162 | entrante | VP paquetes de captura SNMP 


| 1527 | exclusivamente para uso interno | Puerto de base de datos Derby, sólo entre este equipo y él mismo, no se aceptan conexiones externas -- sólo conexiones internas 


| 443 | bidireccional | Se utiliza para las conexiones a clústeres de ONTAP 
|===
* *Compatibilidad con certificados firmados por la entidad de certificación (CA).* las herramientas de ONTAP para VMware vSphere admiten certificados firmados por CA. Vea esto https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/VSC_and_VASA_Provider/Virtual_Storage_Console%3A_Implementing_CA_signed_certificates["artículo de base de conocimientos"^] si quiere más información.
* *Registro de auditoría.* los paquetes de soporte se pueden descargar y son extremadamente detallados. Las herramientas de ONTAP registran toda la actividad de inicio de sesión y cierre de sesión de los usuarios en un archivo de registro independiente. Las llamadas de API VASA se registran en un registro de auditoría de VASA dedicado (cxf.log local).
* *Políticas de contraseña.* se siguen las siguientes directivas de contraseñas:
+
** Las contraseñas no han iniciado sesión en ningún archivo de registro.
** Las contraseñas no se comunican en texto sin formato.
** Las contraseñas se configuran durante el propio proceso de instalación.
** El historial de contraseñas es un parámetro configurable.
** La antigüedad mínima de la contraseña se establece en 24 horas.
** El proceso de finalización automática de los campos de contraseña está desactivado.
** Las herramientas de ONTAP cifran toda la información de credenciales almacenada mediante el hash SHA256.



