---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-datastores-fg.html 
keywords: vSphere, datastore, NFS, nconnect, FlexGroup, session trunking 
summary: Esta página describe las mejores prácticas para implementar volúmenes de ONTAP FlexGroup en un entorno de VMware vSphere. 
---
= Volúmenes de FlexGroup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Utilice ONTAP y FlexGroup Volumes con VMware vSphere para obtener almacenes de datos sencillos y escalables que aprovechan toda la potencia de todo un clúster de ONTAP.

ONTAP 9,8, junto con las herramientas de ONTAP para VMware vSphere 9,8-9,13 y el complemento SnapCenter para VMware 4,4, y otras versiones más recientes, añadieron compatibilidad con almacenes de datos respaldados por volúmenes de FlexGroup en vSphere. Los volúmenes FlexGroup simplifican la creación de grandes almacenes de datos y crean automáticamente los volúmenes constituyentes distribuidos necesarios en el clúster ONTAP para obtener el rendimiento máximo de un sistema ONTAP.

Utilice FlexGroup Volumes con vSphere si necesita un único almacén de datos de vSphere escalable con la potencia de un clúster ONTAP completo, o si cuenta con cargas de trabajo de clonado muy grandes que pueden beneficiarse del mecanismo de clonado de FlexGroup manteniendo constantemente la memoria caché de clonado caliente.



== Descarga de copias

Además de las amplias pruebas del sistema con cargas de trabajo de vSphere, ONTAP 9,8 añadió un nuevo mecanismo de descarga de copia para los almacenes de datos de FlexGroup. Este nuevo sistema emplea un motor de copia mejorado para replicar archivos entre componentes en segundo plano a la vez que permite el acceso al origen y al destino. A continuación, esta caché local de componente se utiliza para crear rápidamente instancias de clones de equipos virtuales bajo demanda.

Para habilitar la descarga de copias optimizada para FlexGroup, consulte https://kb.netapp.com/onprem/ontap/dm/VAAI/How_to_Configure_ONTAP_FlexGroups_to_allow_VAAI_copy_offload["Cómo configurar volúmenes de ONTAP FlexGroup para permitir la descarga de la copia de VAAI"]

Puede ocurrir que si utiliza la clonación de VAAI, pero no clona lo suficiente para mantener la caché caliente, es posible que los clones no sean más rápidos que una copia basada en host. Si ese es el caso, puede ajustar el tiempo de espera de la caché para adaptarse mejor a sus necesidades.

Considere el siguiente escenario:

* Ha creado un nuevo FlexGroup con 8 componentes
* El tiempo de espera de caché para el nuevo FlexGroup se establece en 160 minutos


En esta situación, los primeros 8 clones que se realizarán serán copias completas, no clones de archivos locales. Cualquier clonación adicional de ese equipo virtual antes de que caduque el tiempo de espera de 160 segundos utilizará el motor de clonado de archivos dentro de cada componente en turno rotatorio para crear copias casi inmediatas distribuidas uniformemente en los volúmenes constituyentes.

Cada trabajo de clon nuevo que recibe un volumen restablece el tiempo de espera. Si un volumen constituyente de FlexGroup de ejemplo no recibe una solicitud de clonado antes del tiempo de espera, se borrará la caché de esa máquina virtual en particular y el volumen se deberá volver a completar. Además, si el origen del clon original cambia (por ejemplo, ha actualizado la plantilla), la caché local de cada componente se invalidará para evitar cualquier conflicto. Como se ha indicado anteriormente, la caché se puede ajustar y se puede configurar para satisfacer las necesidades del entorno.

Para obtener más información sobre el uso de FlexGroup Volumes con VAAI, consulte este artículo de la base de conocimientos: https://kb.netapp.com/?title=onprem%2Fontap%2Fdm%2FVAAI%2FVAAI%3A_How_does_caching_work_with_FlexGroups%253F["VAAI: ¿Cómo funciona el almacenamiento en caché con volúmenes FlexGroup?"^]

En entornos donde no es posible aprovechar al máximo la caché FlexGroup, pero aún así requerir un clonado rápido entre volúmenes, considere el uso de vVols. La clonación entre volúmenes con vVols es mucho más rápida que el uso de almacenes de datos tradicionales y no utiliza una caché.



== Configuración de calidad de servicio

Se admite la configuración de la calidad de servicio en el nivel de FlexGroup mediante ONTAP System Manager o el shell del clúster; sin embargo, no se proporciona para la máquina virtual ni la integración con vCenter.

La calidad de servicio (IOPS máx./mín.) se puede establecer en máquinas virtuales individuales o en todas las máquinas virtuales de un almacén de datos en ese momento en la interfaz de usuario de vCenter o mediante las API de REST con las herramientas de ONTAP. La configuración de la calidad de servicio en todas las máquinas virtuales sustituye cualquier configuración independiente por cada máquina virtual. Los ajustes no amplían en el futuro a máquinas virtuales nuevas o migradas; establezca la calidad de servicio en las nuevas máquinas virtuales o vuelva a aplicar la calidad de servicio a todas las máquinas virtuales del almacén de datos.

Tenga en cuenta que VMware vSphere trata todas las I/O de un almacén de datos NFS como una única cola por host, y la limitación de la calidad de servicio de un equipo virtual puede afectar al rendimiento de otras máquinas virtuales del mismo almacén de datos en ese host. Esto contrasta con vVols, que puede mantener su configuración de política de calidad de servicio si migran a otro almacén de datos y no afecta la I/O de otras máquinas virtuales cuando se acelera.



== Métricas

ONTAP 9,8 también agregó nuevas métricas de rendimiento basadas en archivos (IOPS, rendimiento y latencia) para archivos FlexGroup. Estas métricas pueden visualizarse en la consola de herramientas de ONTAP para la consola de VMware vSphere e informes de VM. Las herramientas de ONTAP para el complemento VMware vSphere también le permiten establecer reglas de calidad de servicio (QoS) con una combinación de IOPS máximo o mínimo. Estos conjuntos se pueden establecer en todas las máquinas virtuales de un almacén de datos o individualmente para máquinas virtuales específicas.



== Mejores prácticas

* Utilice las herramientas de ONTAP para crear almacenes de datos de FlexGroup a fin de garantizar que el FlexGroup se cree de forma óptima y que las políticas de exportación se configuren en consonancia con su entorno vSphere. Sin embargo, después de crear el volumen FlexGroup con herramientas de ONTAP, se dará cuenta de que todos los nodos del clúster de vSphere utilizan una sola dirección IP para montar el almacén de datos. Esto podría provocar un cuello de botella en el puerto de red. Para evitar este problema, desmonte el almacén de datos y vuelva a montarlo mediante el asistente para almacenes de datos estándar de vSphere mediante un nombre DNS round-robin que equilibre la carga entre las LIF en la máquina virtual de almacenamiento. Tras el montaje, las herramientas de ONTAP podrán volver a gestionar el almacén de datos. Si no hay herramientas de ONTAP disponibles, use los valores predeterminados de FlexGroup y cree la política de exportación siguiendo las directrices de link:vmware-vsphere-datastores-nfs.html["Almacenes de datos y protocolos: NFS"].
* Al ajustar el tamaño a un almacén de datos FlexGroup, tenga en cuenta que FlexGroup consta de varios volúmenes FlexVol más pequeños que crean un espacio de nombres mayor. De este modo, configure el tamaño del almacén de datos para que sea al menos 8x (asumiendo los 8 componentes predeterminados) el tamaño del archivo VMDK más grande y un margen no utilizado del 10 al 20% para permitir flexibilidad en el reequilibrio. Por ejemplo, si tiene un VMDK de 6TB GB en el entorno, ajuste el tamaño del almacén de datos FlexGroup como mínimo 52,8TB (6x8+10 %).
* VMware y NetApp admiten el trunking de sesiones NFSv4,1 a partir de ONTAP 9.14.1. Consulte las notas de la herramienta de matriz de interoperabilidad (IMT) de NFS 4,1 de NetApp para ver detalles específicos de la versión. NFSv3 no admite varias rutas físicas de un volumen, pero admite nconnect a partir de vSphere 8.0U2. Puede encontrar más información sobre nconnect en el link:https://docs.netapp.com/us-en/netapp-solutions/vmware/vmware-vsphere8-nfs-nconnect.html["NFSv3 Función nConnect con NetApp y VMware"].
* Use el plugin de NFS para VAAI de VMware para la descarga de copias. Tenga en cuenta que, aunque el clonado se mejora dentro de un almacén de datos de FlexGroup, como se ha mencionado anteriormente, ONTAP no ofrece importantes ventajas de rendimiento con respecto a la copia del host ESXi al copiar máquinas virtuales entre FlexVol y/o volúmenes de FlexGroup. Por tanto, tenga en cuenta las cargas de trabajo de clonado cuando decida usar volúmenes de VAAI o FlexGroup. La modificación del número de volúmenes constituyentes es una forma de optimizar para la clonación basada en FlexGroup. Al igual que el ajuste del timeout de caché mencionado anteriormente.
* Utilice herramientas de ONTAP para VMware vSphere 9,8-9,13 para supervisar el rendimiento de las VM de FlexGroup mediante métricas de ONTAP (informes de la consola y de VM), y para gestionar la calidad de servicio en máquinas virtuales individuales. Estas métricas no están disponibles a través de los comandos o las API de ONTAP.
* El plugin de SnapCenter para VMware vSphere versión 4,4 y versiones posteriores admite el backup y la recuperación de máquinas virtuales en un almacén de datos FlexGroup en el sistema de almacenamiento principal. SCV 4,6 añade compatibilidad con SnapMirror para almacenes de datos basados en FlexGroup. La forma más eficiente de proteger los datos es usar copias Snapshot y replicación basadas en cabinas.

