---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-overview.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: ONTAP ha sido una solución de almacenamiento líder para entornos de VMware vSphere durante casi dos décadas y continúa añadiendo funcionalidades innovadoras para simplificar la gestión al tiempo que reduce los costes. Este documento presenta la solución ONTAP para vSphere, e incluye la información de producto más reciente y las prácticas recomendadas para simplificar la puesta en marcha, reducir el riesgo y simplificar la gestión. 
---
= VMware vSphere con ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP ha servido como solución de almacenamiento líder para VMware vSphere y, más recientemente, entornos de Cloud Foundation desde su introducción en el centro de datos moderno en 2002. Sigue introduciendo funciones innovadoras que simplifican la gestión y reducen los costes.

Este documento presenta la solución ONTAP para vSphere, donde se destaca la información de producto más reciente y las prácticas recomendadas para simplificar la puesta en marcha, mitigar los riesgos y simplificar la gestión.


NOTE: Esta documentación sustituye a los informes técnicos publicados anteriormente _TR-4597: VMware vSphere para ONTAP_

Las prácticas recomendadas complementan otros documentos, como guías y listas de compatibilidad. Se desarrollan según pruebas de laboratorio y una amplia experiencia de campo por parte de ingenieros y clientes de NetApp. Puede que no sean las únicas prácticas compatibles que funcionan en todos los entornos, pero suelen ser las soluciones más sencillas que satisfacen las necesidades de la mayoría de los clientes.

Este documento se centra en las funcionalidades de los lanzamientos recientes de ONTAP (9.x) ejecutados en vSphere 7,0 o posterior. Consulte la https://imt.netapp.com/matrix/#search["Herramienta de matriz de interoperabilidad (IMT)"^] y https://www.vmware.com/resources/compatibility/search.php?deviceCategory=san["Guía de compatibilidad de VMware"^] para obtener detalles relacionados con versiones específicas.
