---
sidebar: sidebar 
permalink: vmware/vmware-srm-deployment_best_practices.html 
keywords: vmware, site, recovery manager, vsrm, svm, layout, segmentation, smt, best, practices, deploy, ontap, tools, vvols, srm, vlsr 
summary: 'Con ONTAP, el concepto de las máquinas virtuales de almacenamiento (SVM) proporciona una segmentación estricta en entornos multi-tenant seguros.' 
---
= Mejores prácticas de puesta en marcha
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Las siguientes secciones describen las mejores prácticas para la puesta en marcha con ONTAP y VMware SRM.



== Utilice la versión más reciente de las herramientas de ONTAP 10

ONTAP TOOLS 10 proporciona mejoras significativas con respecto a versiones anteriores, como las siguientes:

* conmutación por error de prueba 8x veces más rápida*
* limpieza y reprotección 2x veces más rápidas*
* 32% más rápido de failover*
* Mayor escala
* Compatibilidad nativa para diseños de sitios compartidos


*Estas mejoras se basan en pruebas internas y pueden variar en función de su entorno.



== Distribución y segmentación de SVM para SMT

Con ONTAP, el concepto de las máquinas virtuales de almacenamiento (SVM) proporciona una segmentación estricta en entornos multi-tenant seguros. Los usuarios de SVM en una SVM no pueden acceder a los recursos ni gestionarlos desde otra. De este modo, puede aprovechar la tecnología ONTAP creando SVM independientes para diferentes unidades de negocio que gestionan sus propios flujos de trabajo de SRM en el mismo clúster para mejorar la eficiencia general del almacenamiento.

Considere la posibilidad de gestionar ONTAP mediante cuentas de ámbito SVM y LIF de administración de SVM para no solo mejorar los controles de seguridad, sino también mejorar el rendimiento. El rendimiento es inherentemente mayor cuando se usan conexiones de ámbito SVM porque el SRA no es necesario para procesar todos los recursos de todo un clúster, incluidos los recursos físicos. En su lugar, solo debe comprender los activos lógicos que se abstraen a una SVM en particular.



== Prácticas recomendadas para gestionar sistemas ONTAP 9

Como se ha mencionado anteriormente, puede gestionar clústeres de ONTAP utilizando credenciales de ámbito de clúster o de SVM y LIF de gestión. Para obtener un rendimiento óptimo, es posible que desee considerar el uso de las credenciales del ámbito SVM siempre que no utilice vVols. Sin embargo, al hacerlo, debe conocer algunos requisitos y perder algunas funciones.

* La cuenta de SVM predeterminada de vsadmin no tiene el nivel de acceso requerido para realizar tareas de las herramientas de ONTAP. Por lo tanto, debe crear una cuenta de SVM nueva. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-user-role-and-privileges.html["Configure los roles y privilegios de usuario de ONTAP"] Usando el archivo JSON incluido. Puede utilizarse para cuentas de SVM o de ámbito de clúster.
* Dado que el complemento de interfaz de usuario de vCenter, VASA Provider y el servidor SRA son microservicios totalmente integrados, debe añadir almacenamiento al adaptador de SRA en SRM de la misma manera que añade almacenamiento en la interfaz de usuario de vCenter para las herramientas de ONTAP. De lo contrario, es posible que el servidor SRA no reconozca las solicitudes que se envían desde el SRM a través del adaptador SRA.
* La comprobación de rutas de NFS no se realiza con credenciales de ámbito SVM, a menos que primero https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["clústeres incorporados"] en el administrador de herramientas de ONTAP y las asocie a vCenter. Esto se debe a que la ubicación física se abstrae de forma lógica de la SVM. Sin embargo, este no es un motivo de preocupación, ya que los sistemas ONTAP modernos ya no sufren una disminución notable del rendimiento cuando se utilizan rutas indirectas.
* Es posible que no se informe del ahorro de espacio agregado debido a la eficiencia del almacenamiento.
* Si es compatible, los duplicados de uso compartido de carga no se pueden actualizar.
* Es posible que no se realicen registros de EMS en sistemas ONTAP gestionados con credenciales de ámbito de SVM.

