---
sidebar: sidebar 
permalink: vmware/vmware-srm-overview.html 
keywords: ontap, vsphere, srm, srm, hybrid, cloud, migration, vmware, site, recovery manager, vsrm,VLSR 
summary: 'La solución ONTAP para la recuperación de sitios en directo (VLSR) y el administrador de recuperación de sitios (SRM) de VMware' 
---
= Recuperación de sitios en vivo de VMware con ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP ha sido una solución de almacenamiento líder para VMware vSphere y, más recientemente, Cloud Foundation, desde que ESX se introdujo en los centros de datos modernos hace más de dos décadas.  NetApp continúa introduciendo sistemas innovadores, como la última generación de la serie ASA A, junto con funciones como la sincronización activa SnapMirror .  Estos avances simplifican la gestión, mejoran la resiliencia y reducen el costo total de propiedad (TCO) de su infraestructura de TI.

Este documento presenta la solución ONTAP para VMware Live Site Recovery (VLSR), anteriormente conocido como Site Recovery Manager (SRM), el software de recuperación ante desastres (DR) líder en la industria de VMware, que incluye la información más reciente del producto y las mejores prácticas para optimizar la implementación, reducir el riesgo y simplificar la gestión continua.


NOTE: Esta documentación reemplaza el informe técnico publicado anteriormente _TR-4900: VMware Site Recovery Manager con ONTAP_

Las prácticas recomendadas complementan otros documentos como guías y herramientas de compatibilidad. Se desarrollan según pruebas de laboratorio y una amplia experiencia de campo por parte de ingenieros y clientes de NetApp. En algunos casos, las prácticas recomendadas pueden no ser la opción adecuada para su entorno; sin embargo, generalmente son las soluciones más sencillas que satisfacen las necesidades del mayor número de clientes.

Este documento se centra en las funcionalidades de los últimos lanzamientos de ONTAP 9 cuando se utiliza junto con las herramientas de ONTAP para VMware vSphere 10,4 (que incluye el adaptador de replicación del almacenamiento de NetApp [SRA] y el proveedor VASA [VP]), así como la recuperación de sitio en activo de VMware 9.



== ¿Por qué usar ONTAP con VLSR o SRM?

Las plataformas de gestión de datos de NetApp impulsadas por ONTAP son algunas de las soluciones de almacenamiento más adoptadas para VLSR.  Las razones son abundantes: una plataforma de gestión de datos segura, de alto rendimiento y con protocolo unificado (NAS y SAN juntos) que proporciona eficiencia de almacenamiento que define la industria, multitenencia, controles de calidad de servicio, protección de datos con instantáneas que ahorran espacio y replicación con SnapMirror.  Todo ello aprovechando la integración nativa de múltiples nubes híbridas para la protección de las cargas de trabajo de VMware y una gran cantidad de herramientas de automatización y orquestación a su alcance.

Cuando utiliza SnapMirror para la replicación basada en matrices, aprovecha una de las tecnologías más probadas y maduras de ONTAP.  SnapMirror le ofrece la ventaja de realizar transferencias de datos seguras y altamente eficientes, copiando únicamente bloques del sistema de archivos modificados, no máquinas virtuales o almacenes de datos completos.  Incluso esos bloques aprovechan los ahorros de espacio, como la deduplicación, la compresión y la compactación.  Los sistemas ONTAP modernos ahora utilizan SnapMirror independiente de la versión, lo que le permite flexibilidad al seleccionar sus clústeres de origen y destino.  SnapMirror se ha convertido verdaderamente en una de las herramientas más poderosas disponibles para la recuperación ante desastres.

Ya sea que utilice almacenes de datos tradicionales conectados a NFS, iSCSI o Fibre Channel (ahora con soporte para almacenes de datos vVols ), VLSR proporciona una oferta sólida de primera mano que aprovecha lo mejor de las capacidades de ONTAP para la recuperación ante desastres o la planificación y orquestación de la migración del centro de datos.



== Aprovechamiento de VLSR ONTAP 9

VLSR aprovecha las tecnologías avanzadas de gestión de datos de los sistemas de ONTAP al integrarse con herramientas de ONTAP para VMware vSphere, un dispositivo virtual que incluye tres componentes principales:

* El complemento de herramientas de ONTAP para vCenter, anteriormente conocido como consola de almacenamiento virtual (VSC), simplifica las funciones de eficiencia y gestión del almacenamiento, mejora la disponibilidad y reduce los costes de almacenamiento y la sobrecarga operativa, tanto si utiliza SAN como NAS. Utiliza prácticas recomendadas para aprovisionar almacenes de datos y optimiza la configuración de host ESXi para entornos de almacenamiento en bloques y NFS. Para obtener todos estos beneficios, NetApp recomienda este plugin cuando se utiliza vSphere con sistemas que ejecutan ONTAP.
* Las herramientas de ONTAP VASA Provider admiten las API de VMware vStorage para el marco de conocimiento del almacenamiento (VASA). EL proveedor DE VASA conecta vCenter Server con ONTAP para ayudar en el aprovisionamiento y la supervisión del almacenamiento de máquinas virtuales. Esto ha permitido el soporte de VMware Virtual Volumes (vVols) y la gestión de políticas de almacenamiento de VM y el rendimiento de vVols individuales de VM. También proporciona alarmas para controlar la capacidad y el cumplimiento de los perfiles.
* El SRA se usa junto con el VLSR para gestionar la replicación de datos de máquinas virtuales entre sitios de producción y recuperación ante desastres para almacenes de datos VMFS tradicionales y NFS, y también para las pruebas no disruptivas de réplicas de recuperación ante desastres. Ayuda a automatizar las tareas de identificación, recuperación y protección. Incluye tanto un dispositivo de servidor SRA como adaptadores SRA para el servidor SRM de Windows y el dispositivo VLSR.


Después de haber instalado y configurado los adaptadores SRA en el servidor VLSR para proteger almacenes de datos que no sean vVols, puede comenzar la tarea de configurar su entorno vSphere para la recuperación ante desastres.

El SRA proporciona una interfaz de comando y control para que el servidor VLSR gestione los volúmenes de ONTAP FlexVol que contienen las máquinas virtuales de VMware (VM), además de la replicación de SnapMirror que las protege.

VLSR puede probar su plan de recuperación ante desastres de forma no disruptiva utilizando la tecnología FlexClone , propiedad de NetApp, para realizar clones casi instantáneos de sus almacenes de datos protegidos en su sitio de recuperación ante desastres.  VLSR crea un entorno sandbox para realizar pruebas de forma segura para que su organización y sus clientes estén protegidos en caso de un verdadero desastre, lo que le brinda confianza en la capacidad de su organización para ejecutar una conmutación por error durante un desastre.

En caso de verdadero desastre o incluso de una migración planificada, VLSR permite enviar cualquier cambio de última hora al conjunto de datos mediante una actualización final de SnapMirror (si lo decide). A continuación, interrumpe el reflejo y monta el almacén de datos en los hosts de recuperación ante desastres. En ese momento, las máquinas virtuales pueden encenderse automáticamente en cualquier orden de acuerdo con la estrategia planificada previamente.


NOTE: Aunque los sistemas ONTAP le permitirán emparejar SVM en el mismo clúster para la replicación de SnapMirror, ese escenario no se ha probado ni certificado con VLSR. Por lo tanto, se recomienda usar solo SVM de diferentes clústeres cuando se utilice VLSR.



== VLSR con ONTAP y otros casos de uso: Cloud híbrido y migración

La integración de su implementación de VLSR con las capacidades de gestión de datos avanzadas de ONTAP permite una escala y un rendimiento enormemente mejorados en comparación con las opciones de almacenamiento local.  Pero más que eso, aporta la flexibilidad de la nube híbrida.  La nube híbrida le permite ahorrar dinero al organizar en niveles los bloques de datos no utilizados desde su matriz de alto rendimiento hasta su hiperescalador preferido usando FabricPool, que podría ser un almacén S3 local como NetApp StorageGRID.  También puede usar SnapMirror para sistemas basados en el borde con ONTAP Select definido por software o DR basado en la nube usando Cloud Volumes ONTAP (CVO) o https://www.equinix.com/partners/netapp["Almacenamiento NetApp en Equinix Metal®"^] , u otros servicios alojados en ONTAP .

Podría entonces hacer una conmutación por error de prueba dentro del centro de datos de un proveedor de servicios en cloud con un espacio de almacenamiento prácticamente nulo gracias a FlexClone. La protección de su empresa ahora puede costar menos que nunca.

VLSR también puede utilizarse para ejecutar migraciones planificadas aprovechando SnapMirror para transferir de forma eficiente sus máquinas virtuales desde un centro de datos a otro o incluso dentro del mismo centro de datos, ya sea el suyo o mediante cualquier otro proveedor de servicios para partners de NetApp.
