---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-datastores-top.html 
keywords: vSphere, datastore, VMFS, FC, NVMe/FC, NVMe/TCP, iSCSI, NFS, vVols 
summary: Esta página describe las mejores prácticas para implementar una solución de almacenamiento de ONTAP en un entorno de VMware vSphere. 
---
= Información general sobre las funciones de protocolo y almacenes de datos de vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se utilizan seis protocolos para conectar VMware vSphere a almacenes de datos en un sistema que ejecuta ONTAP:

* FCP
* NVMe/FC
* NVMe/TCP
* ISCSI
* NFS v3
* NFS v4,1


FCP, NVMe/FC, NVMe/TCP e iSCSI son protocolos de bloque que utilizan el sistema de archivos de máquina virtual de vSphere (VMFS) para almacenar máquinas virtuales dentro de LUN de ONTAP o espacios de nombres de NVMe que se encuentran en un ONTAP FlexVol volume. NFS es un protocolo de archivos que coloca equipos virtuales en almacenes de datos (que son simplemente volúmenes de ONTAP) sin necesidad de VMFS. SMB (CIFS), iSCSI, NVMe/TCP o NFS también se puede utilizar directamente de un sistema operativo invitado a ONTAP.

Las siguientes tablas presentan las características de datastore tradicionales compatibles con vSphere y ONTAP. Esta información no se aplica a datastores vVols, pero generalmente se aplica a vSphere 6.x y versiones posteriores que usan versiones compatibles de ONTAP. También puedes consultar el link:https://configmax.broadcom.com/guest?vmwareproduct=vSphere&release=vSphere%208.0&categories=2-0["Herramienta VMware Configuration Maximums"^] para versiones específicas de vSphere y confirmar límites concretos.

|===
| Característica/función | FC | ISCSI | NVMe-of | NFS 


| Formato | Asignación de dispositivo sin formato (RDM) o VMFS | VMFS o RDM | VMFS | n.a. 


| Número máximo de almacenes de datos o LUN | 1024 LUNs por host ESXi, hasta 32 rutas por LUN, hasta 4096 rutas totales por host, hasta 128 hosts por datastore | 1024 LUNs por host ESXi, hasta 32 rutas por LUN, hasta 4096 rutas totales por host, hasta 128 hosts por datastore | 256 espacios de nombres por host ESXi, hasta 32 rutas por espacio de nombres por host, 2048 rutas totales por host, hasta 16 hosts por datastore | 256 conexiones NFS por host (afectadas por nconnect y trunking de sesiones) NFS predeterminado. MaxVolumes tiene 8 años. Utilice las herramientas de ONTAP para VMware vSphere para aumentar a 256. 


| Tamaño máximo de almacén de datos | 64 TB | 64 TB | 64 TB | 300 TB de volumen FlexVol o superior con volumen FlexGroup 


| Tamaño máximo de archivo del almacén de datos | 62 TB | 62 TB | 62 TB | 62TB con ONTAP 9.12.1P2 y posterior 


| Profundidad de cola óptima por LUN o sistema de archivos | 64-256 | 64-256 | Autonegociar | Consulte NFS.MaxQueueDepth en link:vmware-vsphere-settings.html["Host ESXi recomendado y otra configuración de ONTAP"^]. 
|===
En la siguiente tabla se enumeran las funcionalidades relacionadas con el almacenamiento de VMware admitidas.

|===
| Capacidad/función | FC | ISCSI | NVMe-of | NFS 


| VMotion | Sí | Sí | Sí | Sí 


| VMotion de almacenamiento | Sí | Sí | Sí | Sí 


| Ha de VMware | Sí | Sí | Sí | Sí 


| Planificador de recursos distribuidos de almacenamiento (SDRS) | Sí | Sí | Sí | Sí 


| Software de backup habilitado para VMware vStorage APIs for Data Protection (VADP) | Sí | Sí | Sí | Sí 


| Microsoft Cluster Service (MSCS) o clustering de recuperación tras fallos en un equipo virtual | Sí | Sí ^1^ | Sí ^1^ | No admitido 


| Tolerancia a fallos | Sí | Sí | Sí | Sí 


| Recuperación de sitios activos/Gestor de recuperación de sitios | Sí | Sí | No ^2^ | v3 Solo ^2^ 


| Equipos virtuales con thin provisioning (discos virtuales) | Sí | Sí | Sí | Sí
Esta configuración es la predeterminada para todas las máquinas virtuales de NFS cuando no se utiliza VAAI. 


| Accesos múltiples nativos de VMware | Sí | Sí | Sí | La conexión de enlaces de sesión NFS v4,1 requiere ONTAP 9.14.1 y posterior 
|===
En la siguiente tabla se enumeran las funciones de gestión de almacenamiento de ONTAP admitidas.

|===
| Característica/función | FC | ISCSI | NVMe-of | NFS 


| Deduplicación de datos | Ahorro en la cabina | Ahorro en la cabina | Ahorro en la cabina | De ahorro en el almacén de datos 


| Aprovisionamiento ligero | Almacén de datos o RDM | Almacén de datos o RDM | Almacén de datos | Almacén de datos 


| Redimensión de almacén de datos | Crezca solo | Crezca solo | Crezca solo | Crecer, crecimiento automático y reducción 


| Complementos de SnapCenter para aplicaciones Windows y Linux (en invitado) | Sí | Sí | Sí | Sí 


| Supervisión y configuración del host mediante herramientas de ONTAP para VMware vSphere | Sí | Sí | Sí | Sí 


| Aprovisionar mediante las herramientas de ONTAP para VMware vSphere | Sí | Sí | Sí | Sí 
|===
En la siguiente tabla se enumeran las funciones de backup admitidas.

|===
| Característica/función | FC | ISCSI | NVMe-of | NFS 


| Snapshots de ONTAP | Sí | Sí | Sí | Sí 


| SRM compatible con backups replicados | Sí | Sí | No ^2^ | v3 Solo ^2^ 


| SnapMirror para volúmenes | Sí | Sí | Sí | Sí 


| Acceso a imagen VMDK | Software de backup habilitado para SnapCenter y VADP | Software de backup habilitado para SnapCenter y VADP | Software de backup habilitado para SnapCenter y VADP | El software de backup habilitado para SnapCenter y VADP, vSphere Client y el explorador de almacén de datos de vSphere Web Client 


| Acceso de nivel de ficheros VMDK | Software de backup habilitado para SnapCenter y VADP, solamente Windows | Software de backup habilitado para SnapCenter y VADP, solamente Windows | Software de backup habilitado para SnapCenter y VADP, solamente Windows | Software de backup y aplicaciones de terceros habilitados para SnapCenter y VADP 


| Granularidad de NDMP | Almacén de datos | Almacén de datos | Almacén de datos | Almacén de datos o máquina virtual 
|===
^1^ *NetApp recomienda* usar iSCSI in-guest para clústeres de Microsoft en vez de VMDKs habilitados para multiwriter en un datastore VMFS. Este enfoque está totalmente soportado por Microsoft y VMware, ofrece gran flexibilidad con ONTAP (SnapMirror a sistemas ONTAP locales o en la nube), es fácil de configurar y automatizar, y puede protegerse con SnapCenter. vSphere 7 añade una nueva opción de VMDK en clúster. Esto es diferente de los VMDKs habilitados para multiwriter, que requieren un datastore VMFS 6 con soporte de VMDK en clúster habilitado. Se aplican otras restricciones. Consulta la documentación de VMware link:https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/setup-for-windows-server-failover-clustering.html["Configuración de clústeres de conmutación por error de Windows Server"^] para directrices de configuración.

^2^ Los almacenes de datos que utilizan NVMe-oF y NFS v4,1 requieren replicación de vSphere. Actualmente, SRM no admite la replicación basada en cabinas para NFS v4,1. Actualmente, las herramientas de ONTAP para vSphere Storage Replication Adapter (SRA) de VMware no admiten la replicación basada en cabinas con NVMe-oF.



== Seleccionar un protocolo de almacenamiento

Los sistemas que ejecutan ONTAP son compatibles con todos los principales protocolos de almacenamiento, así que los clientes pueden elegir lo que sea mejor para su entorno, dependiendo de la infraestructura de red existente y planificada y de las habilidades del personal. Históricamente, las pruebas de NetApp generalmente han mostrado poca diferencia entre los protocolos que se ejecutan a velocidades de línea y números de conexiones similares. Sin embargo, NVMe-oF (NVMe/TCP y NVMe/FC) muestra notables mejoras en IOPS, reducción de latencia y hasta un 50% o más de reducción en el consumo de CPU del host por IO de almacenamiento. En el otro extremo del espectro, NFS ofrece la mayor flexibilidad y facilidad de gestión, especialmente para grandes cantidades de máquinas virtuales. Todos estos protocolos pueden usarse y gestionarse con ONTAP tools for VMware vSphere, que proporciona una interfaz sencilla para crear y gestionar datastores.

Los siguientes factores pueden ser útiles a la hora de considerar una opción de protocolo:

* *Entorno operativo actual.* Aunque los EQUIPOS DE TI suelen especializarse en la gestión de la infraestructura IP de Ethernet, no todos tienen experiencia a la hora de gestionar una estructura SAN FC. Sin embargo, es posible que el uso de una red IP de uso general que no está diseñada para el tráfico de almacenamiento no funcione bien. Considere la infraestructura de red de que dispone, las mejoras planificadas y las capacidades y la disponibilidad del personal para gestionarlos.
* *Facilidad de configuración.* más allá de la configuración inicial de la estructura FC (conmutadores y cableado adicionales, zonificación y verificación de interoperabilidad de HBA y firmware), los protocolos de bloque también requieren la creación y asignación de LUN y descubrimiento y formato por parte del SO invitado. Una vez creados y exportados los volúmenes de NFS, el host ESXi los monta y está listo para usarse. NFS no tiene ninguna cualificación de hardware o firmware especial que gestionar.
* *Facilidad de gestión.* Con los protocolos SAN, si necesitas más espacio, hay que seguir varios pasos, como ampliar un LUN, volver a escanear para descubrir el nuevo tamaño y luego ampliar el sistema de archivos. Aunque es posible ampliar un LUN, no se puede reducir el tamaño de un LUN. NFS permite aumentar o reducir el tamaño fácilmente, y este cambio de tamaño puede ser automatizado por el sistema de almacenamiento. SAN ofrece reclamación de espacio a través de los comandos DEALLOCATE/TRIM/UNMAP del sistema operativo invitado, permitiendo que el espacio de los archivos eliminados se devuelva a la cabina. Este tipo de reclamación de espacio no es posible con los datastores NFS.
* *Transparencia del espacio de almacenamiento.* la utilización del almacenamiento suele ser más fácil de ver en entornos NFS, ya que Thin Provisioning devuelve ahorros inmediatamente. Del mismo modo, los ahorros en deduplicación y clonado están disponibles inmediatamente para otras máquinas virtuales en el mismo almacén de datos o para otros volúmenes del sistema de almacenamiento. La densidad de las máquinas virtuales también es superior en un almacén de datos NFS, que puede mejorar el ahorro de la deduplicación y reducir los costes de gestión al tener menos almacenes de datos que gestionar.




== Distribución de almacenes de datos

Los sistemas de almacenamiento ONTAP ofrecen una gran flexibilidad a la hora de crear almacenes de datos para equipos virtuales y discos virtuales. Aunque muchas prácticas recomendadas de ONTAP se aplican al usar las herramientas de ONTAP para aprovisionar almacenes de datos para vSphere (se muestran en la sección link:vmware-vsphere-settings.html["Host ESXi recomendado y otra configuración de ONTAP"]), estas son algunas directrices adicionales a tener en cuenta:

* El despliegue de vSphere con almacenes de datos NFS de ONTAP da como resultado una implementación de alto rendimiento y fácil de gestionar que proporciona ratios de VM por almacén de datos que no se pueden obtener con protocolos de almacenamiento basado en bloques. Esta arquitectura puede resultar en un aumento de diez veces en la densidad del almacén de datos con una reducción correspondiente en el número de almacenes de datos. Aunque un almacén de datos más grande puede beneficiar la eficiencia del almacenamiento y proporcionar beneficios operativos, considera usar al menos cuatro almacenes de datos (FlexVol volumes) por nodo para almacenar tus VMs en un solo controlador ONTAP y así obtener el máximo rendimiento de los recursos de hardware. Este enfoque también te permite establecer almacenes de datos con diferentes políticas de recuperación. Algunos pueden ser respaldados o replicados con más frecuencia que otros según las necesidades del negocio. No se requieren múltiples almacenes de datos con volúmenes FlexGroup para el rendimiento, ya que escalan por diseño.
* *NetApp recomienda* el uso de volúmenes FlexVol para la mayoría de los datastores NFS. A partir de ONTAP 9.8, los volúmenes FlexGroup también se admiten para usarse como datastores y, por lo general, se recomiendan para ciertos casos de uso. Otros contenedores de almacenamiento de ONTAP, como qtrees, generalmente no se recomiendan porque actualmente no son compatibles ni con ONTAP tools for VMware vSphere ni con el plugin NetApp SnapCenter para VMware vSphere.
* Un buen tamaño para un almacén de datos con volúmenes FlexVol es de entre 4 y 8 TB. Este tamaño es un buen punto de equilibrio entre rendimiento, facilidad de gestión y protección de datos. Empiece con poco (digamos, 4 TB) y crezca el almacén de datos según sea necesario (hasta el máximo de 300 TB). Los almacenes de datos más pequeños son más rápidos de recuperar desde un backup o después de un desastre y se pueden mover rápidamente en el clúster. Considere la posibilidad de utilizar el ajuste de tamaño automático de ONTAP para aumentar y reducir automáticamente el volumen a medida que se modifique el espacio utilizado. De forma predeterminada, las herramientas de ONTAP para el asistente de aprovisionamiento de almacenes de datos de VMware vSphere utilizan el tamaño automático para nuevos almacenes de datos. System Manager o la línea de comandos pueden personalizarse los umbrales de crecimiento y reducción, y el tamaño máximo y mínimo.
* Como alternativa, los almacenes de datos VMFS se pueden configurar con espacios de nombres NVMe o LUN (denominados unidades de almacenamiento en nuevos sistemas ASA) a los que se accede mediante FC, iSCSI, NVMe/FC o NVMe/TCP. VMFS permite a los almacenes de datos acceder de forma simultánea a cada servidor ESX de un clúster. Los almacenes de datos VMFS pueden tener un tamaño de hasta 64 TB y constan de hasta 32 LUN de 2 TB (VMFS 3) o una única LUN de 64 TB (VMFS 5). El tamaño máximo de LUN de ONTAP es de 128TB TB en los sistemas AFF, ASA y FAS. NetApp siempre recomienda utilizar un único LUN grande para cada almacén de datos en vez de intentar utilizar extensiones. Al igual que sucede con NFS, considere la posibilidad de utilizar varios almacenes de datos (volúmenes o unidades de almacenamiento) para maximizar el rendimiento en una única controladora de ONTAP.
* Los sistemas operativos invitados (SO) antiguos necesitaban alineación con el sistema de almacenamiento para obtener el mejor rendimiento y eficiencia del almacenamiento. Sin embargo, los sistemas operativos modernos admitidos por el proveedor de distribuidores de Microsoft y Linux como Red Hat ya no requieren ajustes para alinear la partición del sistema de archivos con los bloques del sistema de almacenamiento subyacente en un entorno virtual. Si utiliza un antiguo sistema operativo que pueda requerir la alineación, busque en la base de conocimientos de soporte de NetApp los artículos mediante «alineación de VM» o solicite una copia de TR-3747 a partir de un contacto de ventas o partner de NetApp.
* Evite el uso de utilidades de desfragmentación en el sistema operativo invitado, ya que no ofrece beneficios de rendimiento y afecta a la eficiencia del almacenamiento y al uso del espacio de instantáneas. Considere también desactivar la indización de búsquedas en el sistema operativo invitado para escritorios virtuales.
* ONTAP ha dirigido el sector mediante funciones innovadoras de eficiencia del almacenamiento, que le permiten sacar el máximo partido a su espacio en disco utilizable. Los sistemas AFF llevan esta eficiencia aún más allá gracias a la compresión y la deduplicación inline predeterminadas. Los datos se deduplican en todos los volúmenes de un agregado, por lo que ya no necesita agrupar sistemas operativos similares y aplicaciones similares en un único almacén de datos para optimizar el ahorro.
* En algunos casos, es posible que ni siquiera se necesite un almacén de datos. Piense en sistemas de archivos propiedad del invitado como NFS, SMB, NVMe/TCP o iSCSI gestionados por el invitado. Para obtener orientación específica sobre las aplicaciones, consulte los informes técnicos de NetApp para su aplicación. Por ejemplo, link:../oracle/oracle-overview.html["Bases de datos de Oracle en ONTAP"] tiene una sección sobre la virtualización con detalles útiles.
* Los discos de primera clase (o discos virtuales mejorados) permiten discos gestionados por vCenter independientemente de una máquina virtual con vSphere 6.5 y versiones posteriores. Aunque son gestionados principalmente por la API, pueden ser útiles con vVols, sobre todo cuando las herramientas de OpenStack o Kubernetes las gestionan. Son compatibles tanto con ONTAP como con herramientas de ONTAP para VMware vSphere.




== Migración de almacenes de datos y máquinas virtuales

Al migrar las máquinas virtuales desde un almacén de datos existente en otro sistema de almacenamiento a ONTAP, estas son algunas prácticas que deben tenerse en cuenta:

* Use Storage vMotion para mover la mayoría de los equipos virtuales a ONTAP. Este método no solo no es disruptivo para la ejecución de equipos virtuales, sino que también permite funciones de eficiencia del almacenamiento de ONTAP como deduplicación y compresión inline para procesar los datos a medida que migran. Considere usar funcionalidades de vCenter para seleccionar varias máquinas virtuales de la lista de inventario y programar la migración (utilice la tecla Ctrl mientras hace clic en acciones) en un momento adecuado.
* Aunque podrías planificar cuidadosamente una migración a los almacenes de datos de destino apropiados, a menudo es más sencillo migrar en bloque y luego organizar según sea necesario. Podrías querer usar este enfoque para guiar tu migración a diferentes almacenes de datos si tienes necesidades específicas de protección de datos, como diferentes programaciones de Snapshot. Además, una vez que las VMs están en el clúster NetApp, el almacenamiento vMotion puede usar las descargas VAAI para mover VMs entre los almacenes de datos del clúster sin requerir una copia basada en el host. Ten en cuenta que NFS no descarga el almacenamiento vMotion de las VMs encendidas; sin embargo, VMFS sí lo hace.
* Los equipos virtuales que necesitan una migración más cuidadosa incluyen las bases de datos y las aplicaciones que utilizan almacenamiento conectado. En general, considere el uso de las herramientas de la aplicación para gestionar la migración. Para Oracle, considere la posibilidad de utilizar herramientas de Oracle como RMAN o ASM para migrar los archivos de base de datos. Consulte https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-migration-overview.html["Migración de bases de datos de Oracle a sistemas de almacenamiento de ONTAP"^] para obtener más información. Del mismo modo, para SQL Server, plantéese utilizar SQL Server Management Studio o herramientas de NetApp, como SnapManager para SQL Server o SnapCenter.




== Herramientas de ONTAP para VMware vSphere

La práctica recomendada más importante cuando usas vSphere con sistemas que ejecutan ONTAP es instalar y usar el plug-in ONTAP tools for VMware vSphere (anteriormente conocido como Virtual Storage Console). Este plug-in de vCenter simplifica la gestión del almacenamiento, mejora la disponibilidad y reduce los costes de almacenamiento y la sobrecarga operativa, ya sea usando SAN o NAS, en ASA, AFF, FAS o incluso ONTAP Select (una versión definida por software de ONTAP que se ejecuta en una VM de VMware o KVM). Utiliza las mejores prácticas para el aprovisionamiento de datastores y optimiza la configuración del host ESXi para multivía y tiempos de espera de HBA (esto se describe en el apéndice B). Como es un plug-in de vCenter, está disponible para todos los clientes web de vSphere que se conectan al servidor vCenter.

El plugin también le ayuda a utilizar otras herramientas ONTAP en entornos de vSphere. Le permite instalar el complemento de NFS para VMware VAAI, que permite realizar copias de datos descargados en ONTAP para las operaciones de clonado de equipos virtuales, reservar espacio para archivos de disco virtual gruesos y descargar la copia Snapshot de ONTAP.


NOTE: En los clústeres basados en imágenes de vSphere, aún querrás añadir el NFS Plug-In a tu imagen para que no queden fuera de cumplimiento cuando lo instales con ONTAP tools.

Las herramientas de ONTAP también son la interfaz de gestión para numerosas funciones de VASA Provider para ONTAP, compatible con la gestión basada en políticas de almacenamiento con vVols.

En general, *NetApp recomienda* el uso de las herramientas de ONTAP para la interfaz de VMware vSphere en vCenter para aprovisionar almacenes de datos tradicionales y vVols a fin de garantizar que se siguen las mejores prácticas.



== Redes generales

Configurar los ajustes de red cuando usas vSphere con sistemas que ejecutan ONTAP es sencillo y similar a otras configuraciones de red. Aquí tienes algunas cosas a considerar:

* Hay que separar el tráfico de la red de almacenamiento de otras redes. Se puede lograr una red independiente a través de una VLAN dedicada o switches independientes para el almacenamiento. Si la red de almacenamiento comparte rutas físicas como los enlaces ascendentes, puede que necesite calidad de servicio o puertos adicionales para garantizar el ancho de banda suficiente. No conecte los hosts directamente al almacenamiento; utilice switches para que tengan rutas redundantes y permita que VMware HA funcione sin intervención alguna. Consulte link:vmware-vsphere-network.html["Conexión de red directa"] para obtener más información.
* Las tramas gigantes se pueden utilizar si se desean y admiten en la red, especialmente si se utiliza iSCSI. Si se usan, asegúrese de que estén configurados de la misma forma en todos los dispositivos de red, VLAN, etc., en la ruta entre el almacenamiento y el host ESXi. De lo contrario, puede que observe problemas de rendimiento o conexión. La MTU también debe establecerse de forma idéntica en el switch virtual ESXi, el puerto de VMkernel y, además, en los puertos físicos o los grupos de interfaces de cada nodo ONTAP.
* NetApp solo recomienda deshabilitar el control de flujo de red en los puertos de interconexión de clúster de un clúster de ONTAP. NetApp no ofrece otras recomendaciones para seguir las prácticas recomendadas para los puertos de red restantes que se usan para el tráfico de datos. Debe activar o desactivar según sea necesario. Consulte https://www.netapp.com/pdf.html?item=/media/16885-tr-4182pdf.pdf["CONSULTE TR-4182"^] para obtener más información sobre el control de flujo.
* Cuando las cabinas de almacenamiento ESXi y ONTAP están conectadas a redes de almacenamiento Ethernet, *NetApp recomienda* configurar los puertos Ethernet a los que se conectan estos sistemas como puertos periféricos del protocolo de árbol de expansión rápido (RSTP) o mediante la función PortFast de Cisco. *NetApp recomienda* habilitar la función de troncal PortFast de árbol de expansión en entornos que utilizan la característica PortFast de Cisco y que tienen habilitado el troncalización de VLAN 802,1Q para el servidor ESXi o las cabinas de almacenamiento ONTAP.
* *NetApp recomienda* las siguientes mejores prácticas para la agregación de enlaces:
+
** Usa conmutadores que admitan la agregación de enlaces de puertos en dos chasis de conmutador independientes mediante un enfoque de grupo de agregación de enlaces de varios chasis, como el Virtual PortChannel (vPC) de Cisco.
** Deshabilite LACP para los puertos del switch conectados a ESXi a menos que utilice dvSwitch 5.1 o una versión posterior con LACP configurado.
** Utilice LACP para crear agregados de enlaces para sistemas de almacenamiento de ONTAP con grupos de interfaces dinámicas multimodo con puerto o hash IP. Consulte https://docs.netapp.com/us-en/ontap/networking/combine_physical_ports_to_create_interface_groups.html#dynamic-multimode-interface-group["Gestión de redes"^] para obtener más orientación.
** Utilice una política de agrupación de hash IP en ESXi cuando utilice la agregación de enlaces estáticos (por ejemplo, EtherChannel) y vSwitch estándar, o la agregación de enlaces basada en LACP con switches distribuidos de vSphere. Si no se utiliza la agregación de enlaces, utilice en su lugar «Ruta basada en el identificador de puerto virtual de origen».



