---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-why.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: Los clientes seleccionan ONTAP para vSphere con confianza debido a sus soluciones de almacenamiento SAN y NAS unificadas y a la nueva arquitectura de almacenamiento desagregado simplificada, que se incluye en las cabinas All SAN más recientes. Esta plataforma ofrece una protección Snapshot excepcional y sólidas herramientas de gestión. Mediante la descarga de funciones en un almacenamiento dedicado, ONTAP maximiza los recursos del host, reduce los costes y mantiene un rendimiento óptimo. Además, las cargas de trabajo pueden migrarse fácilmente mediante Storage vMotion en VMFS, NFS o vVols. 
---
= ¿Por qué elegir ONTAP para VMware vSphere?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Los clientes seleccionan ONTAP para vSphere con seguridad para las soluciones de almacenamiento SAN y NAS.La nueva arquitectura de almacenamiento desagregado simplificado, que incluye las cabinas All SAN más recientes, ofrece una experiencia más sencilla a los administradores de almacenamiento SAN al tiempo que conserva la mayoría de las integraciones y el conjunto de funciones de los sistemas ONTAP tradicionales. Los sistemas ONTAP ofrecen una protección Snapshot excepcional y sólidas herramientas de gestión. Mediante la descarga de funciones en un almacenamiento dedicado, ONTAP maximiza los recursos del host, reduce los costes y mantiene un rendimiento óptimo. Además, las cargas de trabajo pueden migrarse fácilmente mediante Storage vMotion en VMFS, NFS o vVols.



== Las ventajas de usar ONTAP para vSphere

Hay muchas razones por las que decenas de miles de clientes han seleccionado ONTAP como solución de almacenamiento para vSphere, como un sistema de almacenamiento unificado que admite los protocolos SAN y NAS, sólidas funcionalidades de protección de datos mediante copias Snapshot con gestión eficiente del espacio y una gran cantidad de herramientas para ayudarle a gestionar los datos de aplicaciones. El uso de un sistema de almacenamiento independiente del hipervisor permite descargar numerosas funciones y maximizar su inversión en sistemas de host vSphere. Este método no solo garantiza que los recursos del host se centren en las cargas de trabajo de las aplicaciones, sino que también evita efectos de rendimiento aleatorios en las aplicaciones de operaciones de almacenamiento.

El uso de ONTAP junto con vSphere es una excelente combinación que le permite reducir los gastos en hardware del host y software de VMware. También puede proteger sus datos con un coste menor y un alto rendimiento constante. Dado que las cargas de trabajo virtualizadas son móviles, puede explorar distintos enfoques mediante Storage vMotion para mover equipos virtuales entre almacenes de datos de VMFS, NFS o vVols, todo ello en el mismo sistema de almacenamiento.

Estos son algunos de los factores clave que valoran los clientes en la actualidad:

* *Almacenamiento unificado.* Los sistemas que ejecutan ONTAP se unifican de varias formas significativas. En un principio, este enfoque hacía referencia a los protocolos NAS y SAN, y ONTAP sigue siendo la plataforma líder para SAN junto con su fortaleza original en NAS. En el mundo de vSphere, este enfoque también podría significar un sistema unificado para una infraestructura de puestos de trabajo virtuales (VDI) junto con una infraestructura de servidores virtuales (VSI). Los sistemas que ejecutan ONTAP suelen ser más económicos para VSI que las cabinas empresariales tradicionales y, al mismo tiempo, cuentan con funcionalidades de eficiencia del almacenamiento avanzadas para gestionar VDI en el mismo sistema. ONTAP también unifica varios medios de almacenamiento, desde SSD a SATA, y puede ampliarlos fácilmente al cloud. No es necesario adquirir un sistema operativo de almacenamiento para obtener rendimiento, otro para archivos y otro para cloud. ONTAP los une a todos.
* *Cabina All SAN (ASA).* Los sistemas de ONTAP ASA más recientes (a partir de A1K, A90, A70, A50, A30 y A20) se basan en una nueva arquitectura de almacenamiento que elimina el paradigma de almacenamiento tradicional de ONTAP relativo a la gestión de agregados y volúmenes. Como no hay recursos compartidos del sistema de archivos, no se necesitan volúmenes. Todo el almacenamiento conectado a un par de alta disponibilidad se trata como una zona de disponibilidad de almacenamiento común (SAZ) dentro de la que los LUN y los espacios de nombres de NVMe se aprovisionan como «unidades de almacenamiento» (SUS). Los últimos sistemas ASA han sido diseñados para ser fáciles de gestionar, gracias a una experiencia familiar para los administradores de almacenamiento SAN. Esta nueva arquitectura es ideal para entornos de vSphere, ya que permite una gestión sencilla de los recursos de almacenamiento y ofrece una experiencia simplificada para los administradores de almacenamiento SAN. La arquitectura de ASA también es compatible con la tecnología NVMe over Fabrics (NVMe-oF) más reciente, que proporciona un rendimiento y una escalabilidad aún mayores para las cargas de trabajo de vSphere.
* *Tecnología Snapshot.* ONTAP fue el primero en ofrecer tecnología Snapshot para la protección de datos y sigue siendo la más avanzada en el sector. Este método de protección de datos con un uso eficiente del espacio se ha ampliado para dar soporte a las API de VMware vSphere para la integración de cabinas (VAAI). Esta integración le permite aprovechar las capacidades Snapshot de ONTAP en las operaciones de backup y restauración, y reducir el impacto en su entorno de producción. Este método también permite utilizar copias Snapshot para una rápida recuperación de equipos virtuales, lo que reduce el tiempo y el esfuerzo necesarios para restaurar datos. Además, la tecnología Snapshot de ONTAP se integra con las soluciones Live Site Recovery (VLSR, anteriormente Site Recovery Manager [SRM]) de VMware, por lo que proporciona una estrategia de protección de datos completa para su entorno virtualizado.
* *Gestión basada en volúmenes virtuales y políticas de almacenamiento.* NetApp fue un partner de diseño inicial de VMware en el desarrollo de vSphere Virtual Volumes (vVols), que ofrecía información sobre la arquitectura y compatibilidad temprana con vVols y VMware vSphere APIs for Storage Awareness (VASA). Este enfoque no solo integró la gestión granular de almacenamiento de máquinas virtuales en VMFS, sino que también admitió la automatización del aprovisionamiento de almacenamiento a través de la gestión basada en políticas de almacenamiento. Este enfoque permite a los arquitectos de almacenamiento diseñar pools de almacenamiento con distintas funcionalidades que pueden consumir fácilmente los administradores de máquinas virtuales. ONTAP es líder en el sector del almacenamiento a escala VVol, por lo que admite cientos de miles de vVols en un único clúster, mientras que las cabinas empresariales y los proveedores de cabinas flash más pequeños admiten hasta varios miles de vVols por cabina. NetApp también está impulsando la evolución de la gestión granular de máquinas virtuales con próximas funcionalidades.
* *Eficiencia de almacenamiento.* Aunque NetApp fue el primero en ofrecer deduplicación para cargas de trabajo de producción, esta innovación no fue la primera ni la última en esta área. Comenzó con copias Snapshot, un mecanismo de protección de datos con gestión eficiente del espacio sin efecto en el rendimiento, junto con la tecnología FlexClone para realizar de forma instantánea copias de lectura y escritura de equipos virtuales para producción y uso del backup. NetApp siguió ofreciendo funcionalidades inline, que incluían deduplicación, compresión y deduplicación de bloque cero, para sacar el máximo partido de almacenamiento de SSD de elevado coste. ONTAP también añadió la posibilidad de empacar operaciones de I/O más pequeñas y archivos en un bloque de discos mediante la compactación. La combinación de estas capacidades se ha traducido en que los clientes solían observar ahorros de hasta 5:1 TB en VSI y hasta 30:1 TB en VDI. La generación más reciente de sistemas ONTAP también incluye la compresión y deduplicación aceleradas por hardware, que pueden mejorar aún más la eficiencia del almacenamiento y reducir los costes. Este método permite almacenar más datos en menos espacio, lo que reduce el coste general del almacenamiento y mejora el rendimiento. NetApp tiene tanta confianza en sus funcionalidades de eficiencia del almacenamiento que ofrece un enlace: https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf [garantía de eficiencia^].
* *Multitenancy.* ONTAP ha sido líder en multi-tenancy, lo que le permite crear varias máquinas virtuales de almacenamiento (SVM) en un único clúster. Este enfoque le permite aislar cargas de trabajo y proporcionar diferentes niveles de servicio a diferentes clientes, lo que lo hace ideal para los proveedores de servicios y grandes empresas. La última generación de sistemas ONTAP también incluye soporte para la gestión de la capacidad. Esta función le permite establecer límites de capacidad para cada inquilino, lo que garantiza que ningún inquilino pueda consumir todos los recursos disponibles. Este enfoque ayuda a garantizar que todos los inquilinos reciban el nivel de servicio que esperan, a la vez que proporciona un alto nivel de seguridad y aislamiento entre los clientes. Además, las funcionalidades de multi-tenancy de ONTAP están integradas con la plataforma vSphere de VMware, lo que le permite gestionar y supervisar fácilmente su entorno virtualizado a través https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["Herramientas de ONTAP para VMware vSphere"] de y. https://docs.netapp.com/us-en/data-infrastructure-insights/["Información sobre la infraestructura de datos"]
* *Cloud híbrido.* tanto si se utiliza para un cloud privado en las instalaciones, una infraestructura de cloud público o un cloud híbrido que combina lo mejor de ambos, las soluciones ONTAP le ayudan a crear su Data Fabric para optimizar y optimizar la gestión de datos. Empiece con sistemas all-flash de alto rendimiento y, a continuación, apítelos con sistemas de disco o de almacenamiento en cloud para protección de datos y cloud computing. Elija entre clouds de Azure, AWS, IBM o Google para optimizar costes y evitar la restricción. Aproveche el soporte avanzado para OpenStack y las tecnologías de contenedor según sea necesario. NetApp también ofrece backup basado en cloud (SnapMirror Cloud, Cloud Backup Service y Cloud Sync) y herramientas de organización en niveles del almacenamiento y archivado (FabricPool) para ONTAP para ayudar a reducir los gastos operativos y aprovechar el amplio alcance del cloud.
* *Y mucho más.* saque partido del rendimiento extremo de las cabinas AFF A-Series de NetApp para acelerar su infraestructura virtualizada a la vez que gestiona los costes. Disfrute de operaciones no disruptivas, desde el mantenimiento hasta las actualizaciones, pasando por la sustitución completa de su sistema de almacenamiento, mediante clústeres ONTAP de escalado horizontal. Proteja los datos en reposo con funcionalidades de cifrado de NetApp sin coste adicional. Asegúrese de que el rendimiento cumple los niveles de servicio empresarial a través de funcionalidades de calidad de servicio de gran precisión. Todos ellos forman parte de la amplia gama de funcionalidades que incluyen ONTAP, el software para la gestión de datos empresariales líder del sector.

