---
sidebar: sidebar 
permalink: vmware/vvols/resources.html 
keywords: tr-4400, vvols, ontap, virtual volumes, protect 
summary:  
---
= Resolución de problemas
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Existen varios recursos de solución de problemas disponibles con información adicional.



== Sitio de soporte de NetApp

Además de una gran variedad de artículos de la base de conocimientos para los productos de virtualización de NetApp, el sitio de soporte de NetApp también ofrece una página de inicio práctica para el https://mysupport.netapp.com/site/products/all/details/otv/docs-tab["Herramientas de ONTAP para VMware vSphere"] producto. Este portal proporciona enlaces a artículos, descargas, informes técnicos y debates sobre soluciones de VMware sobre la comunidad de NetApp. Está disponible en:

https://mysupport.netapp.com/site/products/all/details/otv/docs-tab["_Sitio de soporte de NetApp_"]

Aquí se encuentra disponible documentación adicional sobre la solución:

https://docs.netapp.com/us-en/netapp-solutions/virtualization/index.html["_Soluciones de NetApp para la virtualización_"]



== Solución de problemas del producto

Los distintos componentes de las herramientas de ONTAP, como el complemento vCenter, el proveedor VASA y el adaptador de replicación de almacenamiento, se documentan juntos en el repositorio de documentos de NetApp. Sin embargo, cada uno tiene una subsección independiente de la base de conocimientos y puede tener procedimientos específicos de solución de problemas. Estos solucionan los problemas más comunes que se pueden encontrar con el proveedor VASA.



=== Problemas de interfaz de usuario del proveedor de VASA

Ocasionalmente, vCenter vSphere Web Client encuentra problemas con los componentes de Serenity, lo que hace que no se muestren los elementos de menú VASA Provider for ONTAP. Consulte Resolver problemas de registro del proveedor VASA en la guía de puesta en marcha o esta base de conocimientos https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/VSC_and_VASA_Provider/How_to_resolve_display_issues_with_the_vSphere_Web_Client["artículo"].



=== Error de aprovisionamiento del almacén de datos de vVols

En ocasiones, es posible que se agote el tiempo de espera de los servicios de vCenter al crear el almacén de datos vVols. Para corregirlo, reinicie el servicio vmware-sps y vuelva a montar el almacén de datos vVols mediante los menús de vCenter (Storage > New Datastore). Esto se trata en el error del aprovisionamiento de almacenes de datos de vVols con vCenter Server 6,5 en la guía de administración.



=== La actualización de Unified Appliance no puede montar ISO

Debido a un error en vCenter, es posible que el ISO utilizado para actualizar Unified Appliance de una versión a la siguiente no se pueda montar. Si la ISO se puede conectar al dispositivo en vCenter, siga el proceso en esta base de conocimientos https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/VSC_and_VASA_Provider/Virtual_Storage_Console_(VSC)%3A_Upgrading_VSC_appliance_fails_%22failed_to_mount_ISO%22["artículo"] para solucionar.
