---
sidebar: sidebar 
permalink: epic/epic-example-platforms.html 
keywords: epic,cache,iris 
summary: 'Ejemplo de puesta en marcha de Epic en ONTAP: Protocolos' 
---
= Epic en ONTAP Ejemplo de implementación - plataformas
:allow-uri-read: 


[role="lead"]
Para bases de datos ODB de Epic, diarios y cargas de trabajo de aplicaciones, Epic recomienda presentar el almacenamiento a los servidores como LUN FCP.

NetApp también admite el uso de NVMe/FC (si dispone de versiones de sistemas operativos AIX y RHEL compatibles) y mejora el rendimiento. FCP y NVMe/FC pueden coexistir en la misma estructura.

Los clientes de NetApp han ejecutado con éxito todas las cargas de trabajo de Epic en la nube de Azure.  AWS y Google Cloud también son capaces de ejecutar cargas de trabajo Epic.  NetApp proporciona las capacidades de clase empresarial y el rendimiento necesarios para ejecutar Epic de manera eficaz en la nube.  Las opciones de nube de NetApp ofrecen bloques sobre iSCSI y archivos sobre NFS o SMB.
