---
sidebar: sidebar 
permalink: oracle/dp/oracle-backup-tools.html 
keywords: ontap, data protection 
summary: Herramientas de backup de Oracle y NetApp 
---
= SnapCenter y otras herramientas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
El valor principal de ONTAP en un entorno de aplicaciones proviene de las principales tecnologías de ONTAP, como las copias Snapshot instantáneas, la replicación de SnapMirror sencilla y la creación eficiente de volúmenes FlexClone.

En algunos casos, la simple configuración de estas funciones básicas directamente en ONTAP satisface los requisitos, pero las necesidades más complicadas requieren una capa de orquestación.



== SnapCenter

SnapCenter es el producto estrella de protección de datos de NetApp. A un nivel muy bajo, es similar a los productos de SnapManager en cuanto a cómo se ejecutan backups de bases de datos, pero se creó desde cero para proporcionar un panel único para la gestión de la protección de datos en sistemas de almacenamiento de NetApp.

SnapCenter incluye las funciones básicas como los backups y restauraciones basados en copias Snapshot, la replicación de SnapMirror y SnapVault, y otras funciones necesarias para funcionar a escala para grandes empresas. Estas funciones avanzadas incluyen una funcionalidad ampliada de control de acceso basado en roles (RBAC), API RESTful para integrarse con productos de orquestación de terceros, gestión central no disruptiva de complementos de SnapCenter en hosts de bases de datos y una interfaz de usuario diseñada para entornos a escala de cloud.



== DESCANSO

ONTAP también contiene un amplio conjunto de API RESTful. Esto permite que 3rd proveedores de partes creen protección de datos y otras aplicaciones de gestión con la profunda integración con ONTAP. Además, los clientes que desean crear sus propios flujos de trabajo y utilidades de automatización pueden consumir fácilmente la API RESTful.
