---
sidebar: sidebar 
permalink: mysql/mysql-innodb_io_capacity.html 
keywords: MySQL,MariaDB,innodb_io_capacity 
summary: MySQL en ONTAP 
---
= innodb_io_capacity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En el plug-in InnoDB, se agregó un nuevo parámetro llamado innodb_io_capacity desde MySQL 5,7.

Controla el número máximo de IOPS que realiza InnoDB (lo que incluye la tasa de vaciado de páginas desfasadas y el tamaño de lote [ibuf] del buffer de inserción). El parámetro innodb_io_capacity define un límite superior de IOPS por tareas en segundo plano de InnoDB, como vaciar páginas del pool de buffers y fusionar datos del buffer de cambios.

Defina el parámetro innodb_io_capacity en el número aproximado de operaciones de E/S que el sistema puede realizar por segundo. Lo ideal es mantener la configuración lo más baja posible, pero no tan baja que las actividades en segundo plano se ralenticen. Si el valor es demasiado alto, los datos se eliminan del pool de buffers e insertan el buffer demasiado rápido para que el almacenamiento en caché proporcione una ventaja significativa.


TIP: *NetApp recomienda* que si utiliza esta configuración en NFS, analice el resultado de la prueba de IOPS (SysBench/fio) y establezca el parámetro en consecuencia. Utilice el valor más pequeño posible para vaciar y depurar para mantener el ritmo a menos que vea más páginas modificadas o sucias de las que desee en el pool de buffers de InnoDB.


CAUTION: No utilice valores extremos como 20.000 o más a menos que haya demostrado que los valores más bajos no son suficientes para su carga de trabajo.

El parámetro InnoDB_IO_CAPACITY regula las tasas de vaciado y la E/S relacionada


CAUTION: Puede dañar seriamente el rendimiento si se configura este parámetro o el parámetro innodb_io_capacity_max demasiado alto y se desperdician las operaciones de I/O con vaciado prematuro.
