---
sidebar: sidebar 
permalink: mysql/mysql-innodb_flush_log_at_trx_commit.html 
keywords: MySQL,MariaDB,innodb_flush_log_at_trx_commi 
summary: MySQL e innodb_flush_log_at_trx_commi 
---
= innodb_flush_log_at_trx_commit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se produce un cambio en los datos, este no se escribe inmediatamente en el almacenamiento.

En su lugar, los datos se registran en un buffer de log, que es una parte de la memoria que InnoDB asigna a los cambios de buffer que se registran en el archivo log. InnoDB vacía el buffer en el archivo log cuando se confirma una transacción, cuando el buffer se llena, o una vez por segundo, lo que ocurra primero. La variable de configuración que controla este proceso es innodb_flush_log_at_trx_commit. Las opciones de valor incluyen:

* Cuando lo ajuste `innodb_flush_log_trx_at_commit=0`, InnoDB escribe los datos modificados (en el grupo de buffers de InnoDB) en el archivo log (ib_logfile) y vacía el archivo log (escribir en almacenamiento) cada segundo. Sin embargo, no hace nada cuando se confirma la transacción. Si hay un fallo de alimentación o un bloqueo del sistema, ninguno de los datos sin vaciar es recuperable, ya que no se escribe en el archivo de registro o en las unidades.
* Cuando lo ajuste `innodb_flush_log_trx_commit=1`, InnoDB escribe el buffer de log en el log de transacciones y se vacía en un almacenamiento duradero para cada transacción. Por ejemplo, para todas las confirmaciones de transacciones, InnoDB escribe en el log y, a continuación, escribe en el almacenamiento. Un almacenamiento más lento afecta negativamente al rendimiento; por ejemplo, se reduce el número de transacciones InnoDB por segundo.
* Cuando lo ajuste `innodb_flush_log_trx_commit=2`, InnoDB escribe el buffer de log en el archivo log en cada confirmación; sin embargo, no escribe datos en el almacenamiento. InnoDB vacía los datos una vez cada segundo. Incluso si hay un fallo de alimentación o un fallo del sistema, los datos de la opción 2 están disponibles en el archivo de registro y son recuperables.


Si el rendimiento es el objetivo principal, establezca el valor en 2. Como InnoDB escribe en las unidades una vez por segundo, no por cada confirmación de transacción, el rendimiento mejora drásticamente. Si se produce un fallo en el suministro eléctrico o un fallo, los datos se pueden recuperar del registro de transacciones.

Si la seguridad de los datos es el objetivo principal, establezca el valor en 1 para que, para cada confirmación de transacción, InnoDB se vacíe en las unidades. Sin embargo, el rendimiento puede verse afectado.


TIP: *NetApp recomienda* Establecer el valor innodb_flush_log_trx_commit en 2 para un mejor rendimiento.
