---
sidebar: sidebar 
permalink: mysql/open_file_limits.html 
keywords: MySQL,MariaDB,open_file_limits 
summary: MySQL en ONTAP 
---
= open_file_limits
:allow-uri-read: 


[role="lead"]
La `open_file_limits` el parámetro determina el número de archivos que el sistema operativo permite que mysqld abra.

El valor de este parámetro en tiempo de ejecución es el valor real permitido por el sistema y puede ser diferente del valor especificado al iniciar el servidor. El valor es 0 en sistemas donde MySQL no puede cambiar el número de archivos abiertos. Eficaz `open_files_limit` el valor se basa en el valor especificado en el inicio del sistema (si lo hay) y en los valores de `max_connections` y.. `table_open_cache` mediante el uso de estas fórmulas:

* 10 + `max_connections` + (`table_open_cache` 2)
* `max_connections` 5
* Límite del sistema operativo si es positivo
* Si el límite del sistema operativo es infinito: `open_files_limit` el valor se especifica en el inicio; 5.000 si no hay ninguno


El servidor intenta obtener el número de descriptores de archivo utilizando el máximo de estos cuatro valores. Si no se pueden obtener muchos descriptores, el servidor intenta obtener tantos como el sistema permita.
