---
sidebar: sidebar 
permalink: mysql/overview.html 
keywords: MySQL,MariaDB,TR-4722 
summary: MySQL en ONTAP 
---
= Bases de datos MySQL en ONTAP
:allow-uri-read: 


[role="lead"]
MySQL y sus variantes, incluyendo MariaDB y Percona MySQL, es la base de datos más popular del mundo.


NOTE: Esta documentación sobre ONTAP y la base de datos MySQL sustituye a _TR-4722: Base de datos MySQL sobre las mejores prácticas de NetApp ONTAP que se había publicado anteriormente._

Las características de MySQL incluyen:

* *Bajo TCO.* MySQL es un potente sistema de gestión de bases de datos gratuito y de código abierto que ha estado disponible durante años. Es muy estable. Cuenta con soporte comunitario que ayuda a mantener, depurar y agregar nuevas características. Si una aplicación web requiere más que una base de datos, o requiere equilibrio de carga o sharding, puede configurar fácilmente instancias de base de datos solo con costes de hardware, en lugar de bases de datos comerciales que requieren una única licencia para cada instancia.
* * Fiabilidad, rendimiento y facilidad de uso. * Uno de los distintivos de MySQL es un rendimiento y escalabilidad excepcionales, por lo que muchas empresas basadas en la web lo utilizan. MySQL utiliza varios puntos fuertes clave para ofrecer un rendimiento rápido. Dado que la competencia siempre está a un clic del ratón (o toque de pantalla) de distancia, las respuestas rápidas a las consultas y actividades de los clientes son primordiales. La base de datos que sirve a las aplicaciones basadas en web debe proporcionar un rendimiento extremo tanto para las operaciones de lectura (consultas simples y complejas) como de escritura.
* *Desarrollo, diseño y administración de bases de datos.* MySQL Workbench proporciona un entorno integrado de desarrollo, diseño y administración para que los desarrolladores y los DBA sean más productivos. Diferentes desarrolladores buscan diferentes características en una base de datos, y MySQL ofrece una gama de características. Puede funcionar adecuadamente tanto en un portátil como en un escritorio. Puede adaptarse fácilmente al entorno, asegurando que no choque con los servidores web o aplicaciones existentes.
* *Soporte transaccional integral.* MySQL es uno de los motores de base de datos transaccionales más robustos disponibles. Es la solución para la integridad completa de los datos, ofreciendo características tales como atómico completo, consistente, aislado, soporte de transacción durable; soporte de transacción multiversión; y bloqueo a nivel de hilera sin restricciones. Proporciona identificación inmediata de interbloqueo mediante integridad referencial aplicada por el servidor.
* *Seguridad de datos.* MySQL es mundialmente conocido por ser el sistema de gestión de bases de datos más seguro y confiable utilizado en aplicaciones web populares como WordPress, Drupal, Joomla, Facebook, Google, Google, Google y más. y Twitter. La seguridad de los datos y el soporte para el procesamiento transaccional que acompaña a la versión reciente de MySQL pueden beneficiar a cualquier negocio, especialmente a las empresas de comercio electrónico que implican transferencias de dinero frecuentes.
* *Arquitectura conectable.* La arquitectura del motor de almacenamiento conectable MySQL permite a un profesional de la base de datos seleccionar un motor de almacenamiento especializado para una necesidad de aplicación particular sin tener que gestionar los requisitos de codificación de la aplicación. La arquitectura de servidor MySQL aísla al programador de aplicaciones y al administrador de bases de datos de todos los detalles de implementación de bajo nivel a nivel de almacenamiento, lo que proporciona un modelo de aplicación y una API coherentes y sencillos. Aunque existen distintas funcionalidades en los diferentes motores de almacenamiento, la aplicación está protegida de estas diferencias.


La arquitectura eficiente y modular de MySQL proporciona grandes beneficios si desea dirigirse a una necesidad concreta de una aplicación, como el almacenamiento de datos, el procesamiento de transacciones o situaciones de alta disponibilidad, al tiempo que utiliza interfaces y servicios que son independientes de cualquier motor de almacenamiento.
