---
sidebar: sidebar 
permalink: microsoft/win_deploy_hyperv_slm.html 
keywords: Windows,Hyper-V,VHDX,VM,Virtual 
summary: Cómo configurar la migración dinámica del almacenamiento de Hyper-V. 
---
= Implemente Hyper-V Storage Live Migration
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
Descubre cómo configurar la migración dinámica del almacenamiento de Hyper-V.



== Requisitos previos

* Debe tener un servidor de Hyper-V independiente con almacenamiento independiente (DAS o LUN) o almacenamiento SMB (local o compartido entre otros servidores de Hyper-V.
* El servidor de Hyper-V debe configurarse para la migración dinámica. Revise la sección sobre la implementación en link:win_deploy_hyperv_replica_oce.html["Migración en vivo fuera de un entorno en cluster"].




== Puesta en marcha

. Abra Hyper-V Manager.
. Haga clic con el botón derecho en una máquina virtual y haga clic en Mover.
. Seleccione Mover el almacenamiento de la máquina virtual.
. Seleccione opciones para mover el almacenamiento en función de sus preferencias.
. Proporcione la nueva ubicación para los elementos de la VM.
. Revise el resumen y haga clic en OK para mover el almacenamiento de la máquina virtual.

