---
sidebar: sidebar 
permalink: postgres/postgres-snapcenter-dp.html 
keywords: PostgreSQL,database,postgres 
summary: Software de protección de datos PostgreSQL 
---
= Software de protección de datos PostgreSQL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El complemento de NetApp SnapCenter para base de datos de PostgreSQL, combinado con las tecnologías de Snapshot y FlexClone de NetApp, le ofrece ventajas como:

* Backup y restauración rápidos.
* Clones con gestión eficiente del espacio.
* La capacidad de crear un sistema de recuperación ante desastres rápido y eficaz.


[NOTE]
====
Puede que prefiera elegir los partners de backup premium de NetApp, como Veeam Software y Commvault, bajo las siguientes circunstancias:

* Gestionar cargas de trabajo en un entorno heterogéneo
* Almacenar backups en el cloud o en cinta para su retención a largo plazo
* Soporte para una amplia gama de versiones y tipos de SO


====
El plugin de SnapCenter para PostgreSQL es un plugin de soporte comunitario y la configuración y documentación está disponible en la tienda de automatización de NetApp. Con SnapCenter, el usuario puede realizar backups de la base de datos, clonar y restaurar los datos remotamente.
